adddirection18<-function(img,istart,jstart,d=0){
    row<-nrow(img)
    col<-ncol(img)
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\screening.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate1.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate2.R")
    maxadd18<-0
    { 
     imaxadd18<-0
     jmaxadd18<-0
     imax181i<-0
     jmax181i<-0
     imax182i<-0
     jmax182i<-0
     max1<-0
     max2<-0
     s18<-0
     i<-0
     while((istart+2*i<=row)&&(jstart+3*i<=col)){  
             s18[i+1]<-img[istart+2*i,jstart+3*i]
             i<-i+1
     }
     n<-length(s18)
     screening(n,s18)
     O<-0
     O<-screening(n,s18)$O
     nO<-screening(n,s18)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s18,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s18,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax181i<-istart+2*O[cp1]-2
      jmax181i<-jstart+3*O[cp1]-3
      max1<-NMCD[cp1]
     }
     if(d!=1)
     {
      calculate2(s18,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s18,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax182i<-istart+2*O[cp1]-2
      jmax182i<-jstart+3*O[cp1]-3
      imax182i[2]<-istart+2*O[cp2]-2
      jmax182i[2]<-jstart+3*O[cp2]-3
      max2<-NMCD2[cp1,cp2]
     }
     if(d==1)
     {
      imaxadd18<-imax181i
      jmaxadd18<-jmax181i
      maxadd[18]<-max1
      points(jmaxadd18,row-imaxadd18,pch="。",col="red")
     }
     else if(d==2)
     {
      imaxadd18<-imax182i[1]
      jmaxadd18<-jmax182i[1]
      imaxadd18[2]<-imax182i[2]
      jmaxadd18[2]<-jmax182i[2]
      maxadd18<-max2
      points(jmaxadd18[1],row-imaxadd18[1],pch="。",col="red")
      points(jmaxadd18[2],row-imaxadd18[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imaxadd18<-imax181i
       jmaxadd18<-jmax181i
       maxadd18<-max1
       points(jmaxadd18,row-imaxadd18,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imaxadd18<-imax182i[1]
       jmaxadd18<-jmax32i[1]
       imaxadd18[2]<-imax182i[2]
       jmaxadd18[2]<-jmax182i[2]
       maxadd18<-max2
       points(jmaxadd18[1],row-imaxadd18[1],pch="。",col="red")
       points(jmaxadd18[2],row-imaxadd18[2],pch="。",col="purple")
      }
     } 
    }
}