adddirection6<-function(img,istart,jstart,d=0){
    row<-nrow(img)
    col<-ncol(img)
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\screening.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate1.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate2.R")
    maxadd6<-0
    { 
     imaxadd6<-0
     jmaxadd6<-0
     imax61i<-0
     jmax61i<-0
     imax62i<-0
     jmax62i<-0
     max1<-0
     max2<-0
     s6<-0
     i<-0
     while((istart+2*i<=row)&&(jstart-i>=1)){  
         s6[i+1]<-img[istart+2*i,jstart-i]
         i<-i+1
     }
     n<-length(s6)
     screening(n,s6)
     O<-0
     O<-screening(n,s6)$O
     nO<-screening(n,s6)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s6,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s6,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax61i<-istart+2*O[cp1]-2
      jmax61i<-jstart-O[cp1]+1
      max1<-NMCD[cp1]
     }
     if(d!=1)
     {
      calculate2(s6,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s6,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax62i<-istart+2*O[cp1]-2
      jmax62i<-jstart-O[cp1]+1
      imax62i[2]<-istart+2*O[cp2]-2
      jmax62i[2]<-jstart-O[cp2]+1
      max2<-NMCD2[cp1,cp2]
     }
     if(d==1)
     {
      imaxadd6<-imax31i
      jmaxadd6<-jmax31i
      maxadd6<-max1
      points(jmax6,row-imax6,pch="。",col="red")
     }
     else if(d==2)
     {
      imaxadd6<-imax62i[1]
      jmaxadd6<-jmax62i[1]
      imaxadd6[2]<-imax62i[2]
      jmaxadd6[2]<-jmax62i[2]
      maxadd6<-max2
      points(jmaxadd6[1],row-imaxadd6[1],pch="。",col="red")
      points(jmaxadd6[2],row-imaxadd6[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imaxadd6<-imax31i
       jmaxadd6<-jmax31i
       maxadd6<-max1
       points(jmaxadd6,row-imaxadd6,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imaxadd6<-imax62i[1]
       jmaxadd6<-jmax62i[1]
       imaxadd6[2]<-imax62i[2]
       jmaxadd6[2]<-jmax62i[2]
       maxadd6<-max2
       points(jmaxadd6[1],row-imaxadd6[1],pch="。",col="red")
       points(jmaxadd6[2],row-imaxadd6[2],pch="。",col="purple")
      }
     } 
    }
}