adddirection11<-function(img,istart,jstart,d=0){
    row<-nrow(img)
    col<-ncol(img)
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\screening.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate1.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate2.R")
    maxadd11<-0
    { 
     imaxadd11<-0
     jmaxadd11<-0
     imax111i<-0
     jmax111i<-0
     imax112i<-0
     jmax112i<-0
     max1<-0
     max2<-0
     s11<-0
     i<-0
     while((istart-i>=1)&&(jstart-i>=1)){  
         s11[i+1]<-img[istart-i,jstart-i]
         i<-i+1
     }
     n<-length(s11)
     screening(n,s11)
     O<-0
     O<-screening(n,s11)$O
     nO<-screening(n,s11)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s11,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s11,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax111i<-istart-O[cp1]+1
      jmax111i<-jstart-O[cp1]+1
      max1<-NMCD[cp1]
     }
     if(d!=1)
     {
      calculate2(s11,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s11,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax112i<-istart-O[cp1]+1
      jmax112i<-jstart-O[cp1]+1
      imax112i[2]<-istart-O[cp2]+1
      jmax112i[2]<-jstart-O[cp2]+1
      max2<-NMCD2[cp1,cp2]
     }
     if(d==1)
     {
      imaxadd11<-imax111i
      jmaxadd11<-jmax111i
      maxadd11<-max1
      points(jmaxadd11,row-imaxadd11,pch="。",col="red")
     }
     else if(d==2)
     {
      imaxadd11<-imax112i[1]
      jmaxadd11<-jmax112i[1]
      imaxadd11[2]<-imax112i[2]
      jmaxadd11[2]<-jmax112i[2]
      maxadd11<-max2
      points(jmaxadd11[1],row-imaxadd11[1],pch="。",col="red")
      points(jmaxadd11[2],row-imaxadd11[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imaxadd11<-imax111i
       jmaxadd11<-jmax111i
       maxadd11<-max1
       points(jmaxadd11,row-imaxadd11,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imaxadd11<-imax112i[1]
       jmaxadd11<-jmax112i[1]
       imaxadd11[2]<-imax112i[2]
       jmaxadd11[2]<-jmax112i[2]
       maxadd11<-max2
       points(jmaxadd11[1],row-imaxadd11[1],pch="。",col="red")
       points(jmaxadd11[2],row-imaxadd11[2],pch="。",col="purple")
      }
     } 
    }
}