adddirection3<-function(img,istart,jstart,d=0){
    row<-nrow(img)
    col<-ncol(img)
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\screening.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate1.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate2.R")
    maxadd3<-0
        { 
     imaxadd3<-0
     jmaxadd3<-0
     imax31i<-0
     jmax31i<-0
     imax32i<-0
     jmax32i<-0
     max1<-0
     max2<-0
     s3<-0
     i<-0
     while((istart+i<=row)&&(jstart+i<=col)){  
         s3[i+1]<-img[istart+i,jstart+i]
         i<-i+1
     }
     n<-length(s3)
     screening(n,s3)
     O<-screening(n,s3)$O
     nO<-screening(n,s3)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s3,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s3,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax31i<-istart+O[cp1]-1
      jmax31i<-jstart+O[cp1]-1
      max1<-NMCD[cp1]
     }
     if(d!=1)
     {
      calculate2(s3,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s3,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax32i<-istart+O[cp1]-1
      jmax32i<-jstart+O[cp1]-1
      imax32i[2]<-istart+O[cp2]-1
      jmax32i[2]<-jstart+O[cp2]-1
      max2<-NMCD2[cp1,cp2]
     }
     if(d==1)
     {
      imaxadd3<-imax31i
      jmaxadd3<-jmax31i
      maxadd3<-max1
      points(jmaxadd3,row-imaxadd3,pch="。",col="red")
     }
     else if(d==2)
     {
      imaxadd3<-imax32i[1]
      jmaxadd3<-jmax32i[1]
      imaxadd3[2]<-imax32i[2]
      jmaxadd3[2]<-jmax32i[2]
      maxadd3<-max2
      points(jmaxadd3[1],row-imaxadd3[1],pch="。",col="red")
      points(jmaxadd3[2],row-imaxadd3[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imaxadd3<-imax31i
       jmaxadd3<-jmax31i
       maxadd3<-max1
       points(jmaxadd3,row-imaxadd3,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imaxadd3<-imax32i[1]
       jmaxadd3<-jmax32i[1]
       imaxadd3[2]<-imax32i[2]
       jmaxadd3[2]<-jmax32i[2]
       maxadd3<-max2
       points(jmaxadd3[1],row-imaxadd3[1],pch="。",col="red")
       points(jmaxadd3[2],row-imaxadd3[2],pch="。",col="purple")
      }
     } 
    }
}    
