adddirection12<-function(img,istart,jstart,d=0){
    row<-nrow(img)
    col<-ncol(img)
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\screening.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate1.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate2.R")
    maxadd12<-0
    { 
     imaxadd12<-0
     jmaxadd12<-0
     imax121i<-0
     jmax121i<-0
     imax122i<-0
     jmax122i<-0
     max1<-0
     max2<-0
     s12<-0
     i<-0
     while((istart-2*i>=1)&&(jstart-i>=1)){  
         s12[i+1]<-img[istart-2*i,jstart-i]
         i<-i+1
     }
     n<-length(s12)
     screening(n,s12)
     O<-0
     O<-screening(n,s12)$O
     nO<-screening(n,s12)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s12,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s12,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax121i<-istart-2*O[cp1]+2
      jmax121i<-jstart-O[cp1]+1
      max1<-NMCD[cp1]
     }
     if(d!=1)
     {
      calculate2(s12,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s12,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax122i<-istart-O[cp1]+2
      jmax122i<-jstart-O[cp1]+1
      imax122i[2]<-istart-2*O[cp2]+2
      jmax122i[2]<-jstart-O[cp2]+1
      max2<-NMCD2[cp1,cp2]
     }
     if(d==1)
     {
      imax12<-imax121i
      jmax12<-jmax121i
      max[12]<-max1
      points(jmax12,row-imax12,pch="。",col="red")
     }
     else if(d[12]==2)
     {
      imaxadd12<-imax122i[1]
      jmaxadd12<-jmax122i[1]
      imaxadd12[2]<-imax122i[2]
      jmaxadd12[2]<-jmax122i[2]
      maxadd12<-max2
      points(jmaxadd12[1],row-imaxadd12[1],pch="。",col="red")
      points(jmaxadd12[2],row-imaxadd12[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imaxadd12<-imax121i
       jmaxadd12<-jmax121i
       maxadd12<-max1
       points(jmaxadd12,row-imaxadd12,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imaxadd12<-imax122i[1]
       jmaxadd12<-jmax122i[1]
       imaxadd12[2]<-imax122i[2]
       jmaxadd12[2]<-jmax122i[2]
       maxadd12<-max2
       points(jmax12[1],row-imax12[1],pch="。",col="red")
       points(jmax12[2],row-imax12[2],pch="。",col="purple")
      }
     } 
    }
}