adddirection10<-function(img,istart,jstart,d=0){
    row<-nrow(img)
    col<-ncol(img)
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\screening.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate1.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate2.R")
    maxadd10<-0
    { 
     imaxadd10<-0
     jmaxadd10<-0
     imax101i<-0
     jmax101i<-0
     imax102i<-0
     jmax102i<-0
     max1<-0
     max2<-0
     s10<-0 
     i<-0
     while((istart-i>=1)&&(jstart-2*i>=1)){  
         s10[i+1]<-img[istart-i,jstart-2*i]
         i<-i+1
     }
     n<-length(s10)
     screening(n,s10)
     O<-0
     O<-screening(n,s10)$O
     nO<-screening(n,s10)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s10,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s10,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax101i<-istart-O[cp1]+1
      jmax101i<-jstart-2*O[cp1]+2
      max1<-NMCD[cp1]
     }
     if(d!=1)
     {
      calculate2(s10,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s10,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax102i<-istart-O[cp1]+1
      jmax102i<-jstart-2*O[cp1]+2
      imax102i[2]<-istart-O[cp2]+1
      jmax102i[2]<-jstart-2*O[cp2]+2
      max2<-NMCD2[cp1,cp2]
     }
     if(d==1)
     {
      imaxadd10<-imax101i
      jmaxadd10<-jmax101i
      maxadd10<-max1
      points(jmaxadd10,row-imaxadd10,pch="。",col="red")
     }
     else if(d==2)
     {
      imaxadd10<-imax102i[1]
      jmaxadd10<-jmax102i[1]
      imaxadd10[2]<-imax102i[2]
      jmaxadd10[2]<-jmax102i[2]
      maxadd10<-max2
      points(jmaxadd10[1],row-imaxadd10[1],pch="。",col="red")
      points(jmaxadd10[2],row-imaxadd10[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imaxadd10<-imax101i
       jmaxadd10<-jmax101i
       maxadd10<-max1
       points(jmax10,row-imax10,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imaxadd10<-imax102i[1]
       jmaxadd10<-jmax102i[1]
       imaxadd10[2]<-imax102i[2]
       jmaxadd10[2]<-jmax102i[2]
       maxadd10<-max2
       points(jmaxadd10[1],row-imaxadd10[1],pch="。",col="red")
       points(jmaxadd10[2],row-imaxadd10[2],pch="。",col="purple")
      }
     } 
    }
}