adddirection2<-function(img,istart,jstart,d=0){
    row<-nrow(img)
    col<-ncol(img)
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\screening.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate1.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate2.R")
    maxadd2<-0
    { 
     imaxadd2<-0
     jmaxadd2<-0
     imax21i<-0
     jmax21i<-0
     imax22i<-0
     jmax22i<-0
     max1<-0
     max2<-0
     s2<-0
     i<-0
     while((istart+i<=row)&&(jstart+2*i<=col)){  
         s2[i+1]<-img[istart+i,jstart+2*i]
         i<-i+1
     }
     n<-length(s2)
     screening(n,s2)
     O<-screening(n,s2)$O
     nO<-screening(n,s2)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s2,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s2,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax21i<-istart+O[cp1]-1
      jmax21i<-jstart+2*O[cp1]-2
      max1<-NMCD[cp1]
     }
     if(d!=1)
     {
      calculate2(s2,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s2,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax22i<-istart+O[cp1]-1
      jmax22i<-jstart+2*O[cp1]-2
      imax22i[2]<-istart+O[cp2]-1
      jmax22i[2]<-jstart+2*O[cp2]-2
      max2<-NMCD2[cp1,cp2]
     }
     if(d==1)
     {
      imaxadd2<-imax21i
      jmaxadd2<-jmax21i
      maxadd2<-max1
      points(jmaxadd2,row-imaxadd2,pch="。",col="red")
     }
     else if(d==2)
     {
      imaxadd2<-imax22i[1]
      jmaxadd2<-jmax22i[1]
      imaxadd2[2]<-imax22i[2]
      jmaxadd2[2]<-jmax22i[2]
      maxadd2<-max2
      points(jmaxadd2[1],row-imaxadd2[1],pch="。",col="red")
      points(jmaxadd2[2],row-imaxadd2[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imaxadd2<-imax21i
       jmaxadd2<-jmax21i
       maxadd2<-max1
       points(jmaxadd2,row-imaxadd2,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imaxadd2<-imax22i[1]
       jmaxadd2<-jmax22i[1]
       imaxadd2[2]<-imax22i[2]
       jmaxadd2[2]<-jmax22i[2]
       maxadd2<-max2
       points(jmaxadd2[1],row-imaxadd2[1],pch="。",col="red")
       points(jmaxadd2[2],row-imaxadd2[2],pch="。",col="purple")
      }
     } 
    }
}