adddirection23<-function(img,istart,jstart,d=0){
    row<-nrow(img)
    col<-ncol(img)
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\screening.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate1.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate2.R")
    maxadd23<-0
    { 
     imaxadd23<-0
     jmaxadd23<-0
     imax231i<-0
     jmax231i<-0
     imax232i<-0
     jmax232i<-0
     max1<-0
     max2<-0
     s23<-0
     i<-0
     while((istart+2*i<=row)&&(jstart-3*i>=1)){  
             s23[i+1]<-img[istart+2*i,jstart-3*i]
             i<-i+1
     }
     n<-length(s23)
     screening(n,s23)
     O<-0
     O<-screening(n,s23)$O
     nO<-screening(n,s23)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s23,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s23,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax231i<-istart+2*O[cp1]-2
      jmax231i<-jstart-3*O[cp1]+3
      max1<-NMCD[cp1]
     }
     if(d!=1)
     {
      calculate2(s23,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s23,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax232i<-istart+2*O[cp1]-2
      jmax232i<-jstart-3*O[cp1]+3
      imax232i[2]<-istart+2*O[cp2]-2
      jmax232i[2]<-jstart-3*O[cp2]+3
      max2<-NMCD2[cp1,cp2]
     }
     if(d==1)
     {
      imaxadd23<-imax31i
      jmaxadd23<-jmax31i
      max[23]<-max1
      points(jmaxadd3,row-imaxadd3,pch="。",col="red")
     }
     else if(d==2)
     {
      imaxadd23<-imax232i[1]
      jmaxadd23<-jmax232i[1]
      imaxadd23[2]<-imax232i[2]
      jmaxadd23[2]<-jmax232i[2]
      maxadd23<-max2
      points(jmaxadd23[1],row-imaxadd23[1],pch="。",col="red")
      points(jmaxadd23[2],row-imaxadd23[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imaxadd23<-imax231i
       jmaxadd23<-jmax231i
       maxadd23<-max1
       points(jmaxadd23,row-imaxadd23,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imaxadd23<-imax232i[1]
       jmaxadd23<-jmax232i[1]
       imaxadd23[2]<-imax232i[2]
       jmaxadd23[2]<-jmax232i[2]
       maxadd3<-max2
       points(jmax23add[1],row-imaxadd23[1],pch="。",col="red")
       points(jmax23add[2],row-imaxadd23[2],pch="。",col="purple")
      }
     } 
    }
}