adddirection4<-function(img,istart,jstart,d=0){
    row<-nrow(img)
    col<-ncol(img)
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\screening.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate1.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate2.R")
    maxadd4<-0
    { 
     imaxadd4<-0
     jmaxadd4<-0
     imax41i<-0
     jmax41i<-0
     imax42i<-0
     jmax42i<-0
     max1<-0
     max2<-0
     s4<-0
     i<-0
     while((istart+2*i<=row)&&(jstart+i<=col)){  
         s4[i+1]<-img[istart+2*i,jstart+i]
         i<-i+1
     }
     n<-length(s4)
     screening(n,s4)
     O<-screening(n,s4)$O
     nO<-screening(n,s4)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s4,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s4,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax41i<-istart+2*O[cp1]-2
      jmax41i<-jstart+O[cp1]-1
      max1<-NMCD[cp1]
     }
     if(d!=1)
     {
      calculate2(s4,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s4,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax42i<-istart+2*O[cp1]-2
      jmax42i<-jstart+O[cp1]-1
      imax42i[2]<-istart+2*O[cp2]-2
      jmax42i[2]<-jstart+O[cp2]-1
      max2<-NMCD2[cp1,cp2]
     }
     if(d==1)
     {
      imaxadd4<-imax41i
      jmaxadd4<-jmax41i
      maxadd4<-max1
      points(jmaxadd4,row-imaxadd4,pch="。",col="red")
     }
     else if(d==2)
     {
      imaxadd4<-imax42i[1]
      jmaxadd4<-jmax42i[1]
      imaxadd4[2]<-imax42i[2]
      jmaxadd4[2]<-jmax42i[2]
      maxadd4<-max2
      points(jmaxadd4[1],row-imaxadd4[1],pch="。",col="red")
      points(jmaxadd4[2],row-imaxadd4[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imaxadd4<-imax41i
       jmaxadd4<-jmax41i
       maxadd4<-max1
       points(jmaxadd4,row-imaxadd4,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imaxadd4<-imax42i[1]
       jmaxadd4<-jmax42i[1]
       imaxadd4[2]<-imax42i[2]
       jmaxadd4[2]<-jmax42i[2]
       maxadd4<-max2
       points(jmaxadd4[1],row-imaxadd4[1],pch="。",col="red")
       points(jmaxadd4[2],row-imaxadd4[2],pch="。",col="purple")
      }
     } 
    }
}