adddirection24<-function(img,istart,jstart,d=0){
    row<-nrow(img)
    col<-ncol(img)
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\screening.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate1.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate2.R")
    maxadd24<-0
    { 
     imaxadd24<-0
     jmaxadd24<-0
     imax241i<-0
     jmax241i<-0
     imax242i<-0
     jmax242i<-0
     max1<-0
     max2<-0
     s24<-0
     i<-0
     while((istart+i<=row)&&(jstart-3*i>=1)){  
         s24[i+1]<-img[istart+i,jstart-3*i]
         i<-i+1
     }
     n<-length(s24)
     screening(n,s24)
     O<-0
     O<-screening(n,s24)$O
     nO<-screening(n,s24)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s24,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s24,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax241i<-istart+O[cp1]-1
      jmax241i<-jstart-3*O[cp1]+3
      max1<-NMCD[cp1]
     }
     if(d!=1)
     {
      calculate2(s3,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s3,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax242i<-istart+O[cp1]-1
      jmax242i<-jstart-3*O[cp1]+3
      imax242i[2]<-istart+O[cp2]-1
      jmax242i[2]<-jstart-3*O[cp2]+3
      max2<-NMCD2[cp1,cp2]
     }
     if(d==1)
     {
      imaxadd24<-imax31i
      jmaxadd24<-jmax31i
      maxadd24<-max1
      points(jmaxadd24,row-imaxadd24,pch="。",col="red")
     }
     else if(d==2)
     {
      imaxadd24<-imax242i[1]
      jmaxadd24<-jmax242i[1]
      imaxadd24[2]<-imax242i[2]
      jmaxadd24[2]<-jmax242i[2]
      maxadd24<-max2
      points(jmaxadd24[1],row-imaxadd24[1],pch="。",col="red")
      points(jmaxadd24[2],row-imaxadd24[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imaxadd24<-imax241i
       jmaxadd24<-jmax241i
       maxadd24<-max1
       points(jmaxadd24,row-imaxadd24,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imaxadd24<-imax242i[1]
       jmaxadd24<-jmax242i[1]
       imaxadd24[2]<-imax242i[2]
       jmaxadd24[2]<-jmax242i[2]
       maxadd24<-max2
       points(jmaxadd24[1],row-imaxadd24[1],pch="。",col="red")
       points(jmaxadd24[2],row-imaxadd24[2],pch="。",col="purple")
      }
     } 
    }
}