statsnake1<-function(img,istart,jstart){
    row<-nrow(img)
    col<-ncol(img)
    max<-0
    imax<-0
    jmax<-0
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\screening.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate1.R")
    {                                                                                    #The 1st direction 
     s1<-0
     for(i in jstart:col)    
          s1[i-jstart+1]<-img[istart,i]
     n<-length(s1)
     screening(n,s1)                                                                     #screening process, finding the most influential points
     O<-screening(n,s1)$O
     nO<-screening(n,s1)$nO
     calculate1(s1,n,O,nO,istart,jstart)                                                 #calculate the statistic of the NMCD method
     NMCD<-calculate1(s1,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){                                                                     #locate the changepoint
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax<-istart
     jmax<-jstart+O[summax]-1
     max<-NMCD[summax]
    }
    {                                                                                    #The 2nd direnction
     s2<-0
     i<-0
     while((istart+i<=row)&&(jstart+2*i<=col)){  
         s2[i+1]<-img[istart+i,jstart+2*i]
         i<-i+1
     }
     n<-length(s2)
     screening(n,s2)
     O<-screening(n,s2)$O
     nO<-screening(n,s2)$nO
     calculate1(s2,n,O,nO,istart,jstart)
     NMCD<-calculate1(s2,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[2]<-istart+O[summax]-1
     jmax[2]<-jstart+2*O[summax]-2
     max[2]<-NMCD[summax]
    }
    {                                                                                     #The 3rd direnction
     s3<-0
     i<-0
     while((istart+i<=row)&&(jstart+i<=col)){  
         s3[i+1]<-img[istart+i,jstart+i]
         i<-i+1
     }
     n<-length(s3)
     screening(n,s3)
     O<-screening(n,s3)$O
     nO<-screening(n,s3)$nO
     calculate1(s3,n,O,nO,istart,jstart)
     NMCD<-calculate1(s3,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[3]<-istart+O[summax]-1
     jmax[3]<-jstart+O[summax]-1
     max[3]<-NMCD[summax]
    }
    {                                                                                     #The 4th direnction
     s4<-0
     i<-0
     while((istart+2*i<=row)&&(jstart+i<=col)){  
         s4[i+1]<-img[istart+2*i,jstart+i]
         i<-i+1
     }
     n<-length(s4)
     screening(n,s4)
     O<-screening(n,s4)$O
     nO<-screening(n,s4)$nO
     calculate1(s4,n,O,nO,istart,jstart)
     NMCD<-calculate1(s4,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[4]<-istart+2*O[summax]-2
     jmax[4]<-jstart+O[summax]-1
     max[4]<-NMCD[summax]
    }
    {                                                                                     #The 5th direnction
     s5<-0
     for(i in istart:row)
         s5[i-istart+1]<-img[i,jstart]
     n<-length(s5)
     screening(n,s5)
     O<-0
     O<-screening(n,s5)$O
     nO<-screening(n,s5)$nO
     calculate1(s5,n,O,nO,istart,jstart)
     NMCD<-calculate1(s5,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[5]<-istart+O[summax]-1
     jmax[5]<-jstart
     max[5]<-NMCD[summax]
    }
    {                                                                                     #The 6th direnction
     s6<-0
     i<-0
     while((istart+2*i<=row)&&(jstart-i>=1)){  
         s6[i+1]<-img[istart+2*i,jstart-i]
         i<-i+1
     }
     n<-length(s6)
     screening(n,s6)
     O<-0
     O<-screening(n,s6)$O
     nO<-screening(n,s6)$nO
     calculate1(s6,n,O,nO,istart,jstart)
     NMCD<-calculate1(s6,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[6]<-istart+2*O[summax]-2
     jmax[6]<-jstart-O[summax]+1
     max[6]<-NMCD[summax]
    }
    {                                                                                     #The 7th direnction
     s7<-0
     i<-0
     while((istart+i<=row)&&(jstart-i>=1)){  
         s7[i+1]<-img[istart+i,jstart-i]
         i<-i+1
     }
     n<-length(s7)
     screening(n,s7)
     O<-0
     O<-screening(n,s7)$O
     nO<-screening(n,s7)$nO
     calculate1(s7,n,O,nO,istart,jstart)
     NMCD<-calculate1(s7,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[7]<-istart+O[summax]-1
     jmax[7]<-jstart-O[summax]+1
     max[7]<-NMCD[summax]
    }
    {                                                                                     #The 8th direnction
     s8<-0
     i<-0
     while((istart+i<=row)&&(jstart-2*i>=1)){  
         s8[i+1]<-img[istart+i,jstart-2*i]
         i<-i+1
     }
     n<-length(s8)
     screening(n,s8)
     O<-0
     O<-screening(n,s8)$O
     nO<-screening(n,s8)$nO
     calculate1(s8,n,O,nO,istart,jstart)
     NMCD<-calculate1(s8,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[8]<-istart+O[summax]-1
     jmax[8]<-jstart-2*O[summax]+2
     max[8]<-NMCD[summax]
    }
    {                                                                                     #The 9th direnction
     s9<-0
     for(i in 1:jstart)
         s9[i]<-img[istart,jstart-i+1]
     n<-length(s9)
     screening(n,s9)
     O<-0
     O<-screening(n,s9)$O
     nO<-screening(n,s9)$nO
     calculate1(s9,n,O,nO,istart,jstart)
     NMCD<-calculate1(s9,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[9]<-istart
     jmax[9]<-jstart-O[summax]+1
     max[9]<-NMCD[summax]
    }
    {                                                                                     #The 10th direnction
     s10<-0 
     i<-0
     while((istart-i>=1)&&(jstart-2*i>=1)){  
         s10[i+1]<-img[istart-i,jstart-2*i]
         i<-i+1
     }
     n<-length(s10)
     screening(n,s10)
     O<-0
     O<-screening(n,s10)$O
     nO<-screening(n,s10)$nO
     calculate1(s10,n,O,nO,istart,jstart)
     NMCD<-calculate1(s10,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[10]<-istart-O[summax]+1
     jmax[10]<-jstart-2*O[summax]+2
     max[10]<-NMCD[summax]
    }
    {                                                                                     #The 11th direnction
     s11<-0
     i<-0
     while((istart-i>=1)&&(jstart-i>=1)){  
         s11[i+1]<-img[istart-i,jstart-i]
         i<-i+1
     }
     n<-length(s11)
     screening(n,s11)
     O<-0
     O<-screening(n,s11)$O
     nO<-screening(n,s11)$nO
     calculate1(s11,n,O,nO,istart,jstart)
     NMCD<-calculate1(s11,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[11]<-istart-O[summax]+1
     jmax[11]<-jstart-O[summax]+1
     max[11]<-NMCD[summax]
    }
    {                                                                                     #The 12th direnction
     s12<-0
     i<-0
     while((istart-2*i>=1)&&(jstart-i>=1)){  
         s12[i+1]<-img[istart-2*i,jstart-i]
         i<-i+1
     }
     n<-length(s12)
     screening(n,s12)
     O<-0
     O<-screening(n,s12)$O
     nO<-screening(n,s12)$nO
     calculate1(s12,n,O,nO,istart,jstart)
     NMCD<-calculate1(s12,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[12]<-istart-2*O[summax]+2
     jmax[12]<-jstart-O[summax]+1
     max[12]<-NMCD[summax]
    }
    {                                                                                     #The 13th direnction
     s13<-0
     for(i in 1:istart)
         s13[i]<-img[istart-i+1,jstart]
     n<-length(s13)
     screening(n,s13)
     O<-0
     O<-screening(n,s13)$O
     nO<-screening(n,s13)$nO
     calculate1(s13,n,O,nO,istart,jstart)
     NMCD<-calculate1(s13,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[13]<-istart-O[summax]+1
     jmax[13]<-jstart
     max[13]<-NMCD[summax]
    }
    {
     s14<-0                                                                               #The 14th direnction
     i<-0
     while((istart-2*i>=1)&&(jstart+i<=col)){  
         s14[i+1]<-img[istart-2*i,jstart+i]
         i<-i+1
     }
     n<-length(s14)
     screening(n,s14)
     O<-0
     O<-screening(n,s14)$O
     nO<-screening(n,s14)$nO
     calculate1(s14,n,O,nO,istart,jstart)
     NMCD<-calculate1(s14,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[14]<-istart-2*O[summax]+2
     jmax[14]<-jstart+O[summax]-1
     max[14]<-NMCD[summax]
    }
    {                                                                                     #The 15th direnction
     s15<-0
     i<-0
     while((istart-i>=1)&&(jstart+i<=col)){  
         s15[i+1]<-img[istart-i,jstart+i]
         i<-i+1
     }
     n<-length(s15)
     screening(n,s15)
     O<-0
     O<-screening(n,s15)$O
     nO<-screening(n,s15)$nO
     calculate1(s15,n,O,nO,istart,jstart)
     NMCD<-calculate1(s15,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[15]<-istart-O[summax]+1
     jmax[15]<-jstart+O[summax]-1
     max[15]<-NMCD[summax]
    }
    {                                                                                     #The 16th direnction
     s16<-0
     i<-0
     while((istart-i>=1)&&(jstart+2*i<=col)){  
         s16[i+1]<-img[istart-i,jstart+2*i]
         i<-i+1
     }
     n<-length(s16)
     screening(n,s16)
     O<-0
     O<-screening(n,s16)$O
     nO<-screening(n,s16)$nO
     calculate1(s16,n,O,nO,istart,jstart)
     NMCD<-calculate1(s16,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[16]<-istart-O[summax]+1
     jmax[16]<-jstart+2*O[summax]-2
     max[16]<-NMCD[summax]
    }
    {                                                                                     #The 17th direnction
     s17<-0
     i<-0
     while((istart+i<=row)&&(jstart+3*i<=col)){  
         s17[i+1]<-img[istart+i,jstart+3*i]
         i<-i+1
     }
     n<-length(s17)
     screening(n,s17)
     O<-0
     O<-screening(n,s17)$O
     nO<-screening(n,s17)$nO
     calculate1(s17,n,O,nO,istart,jstart)
     NMCD<-calculate1(s17,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[17]<-istart+O[summax]-1
     jmax[17]<-jstart+3*O[summax]-3
     max[17]<-NMCD[summax]
    }
    {                                                                                     #The 18th direnction
     s18<-0
     i<-0
     while((istart+2*i<=row)&&(jstart+3*i<=col)){  
             s18[i+1]<-img[istart+2*i,jstart+3*i]
             i<-i+1
     }
     n<-length(s18)
     screening(n,s18)
     O<-0
     O<-screening(n,s18)$O
     nO<-screening(n,s18)$nO
     calculate1(s18,n,O,nO,istart,jstart)
     NMCD<-calculate1(s18,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[18]<-istart+2*O[summax]-2
     jmax[18]<-jstart+3*O[summax]-3
     max[18]<-NMCD[summax]
    }
    {                                                                                     #The 19th direnction
     s19<-0
     i<-0
     while((istart+3*i<=row)&&(jstart+2*i<=col)){  
             s19[i+1]<-img[istart+3*i,jstart+2*i]
             i<-i+1
     }
     n<-length(s19)
     screening(n,s19)
     O<-0
     O<-screening(n,s19)$O
     nO<-screening(n,s19)$nO
     calculate1(s19,n,O,nO,istart,jstart)
     NMCD<-calculate1(s19,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[19]<-istart+3*O[summax]-3
     jmax[19]<-jstart+2*O[summax]-2
     max[19]<-NMCD[summax]
    }
    {                                                                                     #The 20th direnction
     s20<-0
     i<-0
     while((istart+3*i<=row)&&(jstart+i<=col)){  
         s20[i+1]<-img[istart+3*i,jstart+i]
         i<-i+1
     }
     n<-length(s20)
     screening(n,s20)
     O<-0
     O<-screening(n,s20)$O
     nO<-screening(n,s20)$nO
     calculate1(s20,n,O,nO,istart,jstart)
     NMCD<-calculate1(s20,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[20]<-istart+3*O[summax]-3
     jmax[20]<-jstart+O[summax]-1
     max[20]<-NMCD[summax]
    }
    {                                                                                     #The 21th direnction
     s21<-0
     i<-0
     while((istart+3*i<=row)&&(jstart-i>=1)){  
         s21[i+1]<-img[istart+3*i,jstart-i]
         i<-i+1
     }
     n<-length(s21)
     screening(n,s21)
     O<-0
     O<-screening(n,s21)$O
     nO<-screening(n,s21)$nO
     calculate1(s21,n,O,nO,istart,jstart)
     NMCD<-calculate1(s21,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[21]<-istart+3*O[summax]-3
     jmax[21]<-jstart-O[summax]+1
     max[21]<-NMCD[summax]
    }
    {                                                                                     #The 22th direnction
     s22<-0
     i<-0
     while((istart+3*i<=row)&&(jstart-2*i>=1)){  
             s22[i+1]<-img[istart+3*i,jstart-2*i]
             i<-i+1
     }
     n<-length(s22)
     screening(n,s22)
     O<-0
     O<-screening(n,s22)$O
     nO<-screening(n,s22)$nO
     calculate1(s22,n,O,nO,istart,jstart)
     NMCD<-calculate1(s22,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[22]<-istart+3*O[summax]-3
     jmax[22]<-jstart-2*O[summax]+2
     max[22]<-NMCD[summax]
    }
    {                                                                                     #The 23th direnction
     s23<-0
     i<-0
     while((istart+2*i<=row)&&(jstart-3*i>=1)){  
             s23[i+1]<-img[istart+2*i,jstart-3*i]
             i<-i+1
     }
     n<-length(s23)
     screening(n,s23)
     O<-0
     O<-screening(n,s23)$O
     nO<-screening(n,s23)$nO
     calculate1(s23,n,O,nO,istart,jstart)
     NMCD<-calculate1(s23,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[23]<-istart+2*O[summax]-2
     jmax[23]<-jstart-3*O[summax]+3
     max[23]<-NMCD[summax]
    }
    {                                                                                     #The 24th direnction
     s24<-0
     i<-0
     while((istart+i<=row)&&(jstart-3*i>=1)){  
         s24[i+1]<-img[istart+i,jstart-3*i]
         i<-i+1
     }
     n<-length(s24)
     screening(n,s24)
     O<-0
     O<-screening(n,s24)$O
     nO<-screening(n,s24)$nO
     calculate1(s24,n,O,nO,istart,jstart)
     NMCD<-calculate1(s24,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[24]<-istart+O[summax]-1
     jmax[24]<-jstart-3*O[summax]+3
     max[24]<-NMCD[summax]
    }
    {                                                                                     #The 25th direnction
     s25<-0
     i<-0
     while((istart-i>=1)&&(jstart-3*i>=1)){  
         s25[i+1]<-img[istart-i,jstart-3*i]
         i<-i+1
     }
     n<-length(s25)
     screening(n,s25)
     O<-0
     O<-screening(n,s25)$O
     nO<-screening(n,s25)$nO
     calculate1(s25,n,O,nO,istart,jstart)
     NMCD<-calculate1(s25,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[25]<-istart-O[summax]+1
     jmax[25]<-jstart-3*O[summax]+3
     max[25]<-NMCD[summax]
    }
    {                                                                                     #The 26th direnction
     s26<-0
     i<-0
     while((istart-2*i>=1)&&(jstart-3*i>=1)){  
             s26[i+1]<-img[istart-2*i,jstart-3*i]
             i<-i+1
     }
     n<-length(s26)
     screening(n,s26)
     O<-0
     O<-screening(n,s26)$O
     nO<-screening(n,s26)$nO
     calculate1(s26,n,O,nO,istart,jstart)
     NMCD<-calculate1(s26,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[26]<-istart-2*O[summax]+2
     jmax[26]<-jstart-3*O[summax]+3
     max[26]<-NMCD[summax]
    }
    {                                                                                     #The 27th direnction
     s27<-0
     i<-0
     while((istart-3*i>=1)&&(jstart-2*i>=1)){  
             s27[i+1]<-img[istart-3*i,jstart-2*i]
             i<-i+1
     }
     n<-length(s27)
     screening(n,s27)
     O<-0
     O<-screening(n,s27)$O
     nO<-screening(n,s27)$nO
     calculate1(s27,n,O,nO,istart,jstart)
     NMCD<-calculate1(s27,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[27]<-istart-3*O[summax]+3
     jmax[27]<-jstart-2*O[summax]+2
     max[27]<-NMCD[summax]
    }
    {                                                                                     #The 28th direnction
     s28<-0
     i<-0
     while((istart-3*i>=1)&&(jstart-i>=1)){  
         s28[i+1]<-img[istart-3*i,jstart-i]
         i<-i+1
     }
     n<-length(s28)
     screening(n,s28)
     O<-0
     O<-screening(n,s28)$O
     nO<-screening(n,s28)$nO
     calculate1(s28,n,O,nO,istart,jstart)
     NMCD<-calculate1(s28,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[28]<-istart-3*O[summax]+3
     jmax[28]<-jstart-O[summax]+1
     max[28]<-NMCD[summax]
    }
    {                                                                                     #The 29th direnction
     s29<-0
     i<-0
     while((istart-3*i>=1)&&(jstart+i<=col)){  
         s29[i+1]<-img[istart-3*i,jstart+i]
         i<-i+1
     }
     n<-length(s29)
     screening(n,s29)
     O<-0
     O<-screening(n,s29)$O
     nO<-screening(n,s29)$nO
     calculate1(s29,n,O,nO,istart,jstart)
     NMCD<-calculate1(s29,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[29]<-istart-3*O[summax]+3
     jmax[29]<-jstart+O[summax]-1
     max[29]<-NMCD[summax]
    }
    {                                                                                     #The 30th direnction
     s30<-0
     i<-0
     while((istart-3*i>=1)&&(jstart+2*i<=col)){  
             s30[i+1]<-img[istart-3*i,jstart+2*i]
             i<-i+1
     }
     n<-length(s30)
     screening(n,s30)
     O<-0
     O<-screening(n,s30)$O
     nO<-screening(n,s30)$nO
     calculate1(s30,n,O,nO,istart,jstart)
     NMCD<-calculate1(s30,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[30]<-istart-3*O[summax]+3
     jmax[30]<-jstart+2*O[summax]-2
     max[30]<-NMCD[summax]
    }
    {                                                                                     #The 31th direnction
     s31<-0
     i<-0
     while((istart-2*i>=1)&&(jstart+3*i<=col)){  
             s31[i+1]<-img[istart-2*i,jstart+3*i]
             i<-i+1
     }
     n<-length(s31)
     screening(n,s31)
     O<-0
     O<-screening(n,s31)$O
     nO<-screening(n,s31)$nO
     calculate1(s31,n,O,nO,istart,jstart)
     NMCD<-calculate1(s31,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[31]<-istart-2*O[summax]+2
     jmax[31]<-jstart+3*O[summax]-3
     max[31]<-NMCD[summax]
    }
    {                                                                                     #The 32th direnction
     s32<-0
     i<-0
     while((istart-i>=1)&&(jstart+3*i<=col)){  
         s32[i+1]<-img[istart-i,jstart+3*i]
         i<-i+1
     }
     n<-length(s32)
     screening(n,s32)
     O<-0
     O<-screening(n,s32)$O
     nO<-screening(n,s32)$nO
     calculate1(s32,n,O,nO,istart,jstart)
     NMCD<-calculate1(s32,n,O,nO,istart,jstart)$NMCD
     NMCD1<-matrix(0,nrow=nO)
     for(a in 1:nO){    
         if(NMCD[a]!=0)
             NMCD1[a]<-1/NMCD[a]
         else
             NMCD1[a]<-NMCD[a]
     }
     summax<-which(NMCD1==min(NMCD1))
     imax[32]<-istart-O[summax]+1
     jmax[32]<-jstart+3*O[summax]-3
     max[32]<-NMCD[summax]
    }
    for(i in 1:32)
        points(jmax[i],row-imax[i],pch="¡£",col="red")
    changepoints<-cbind(imax,jmax)
    colnames(changepoints)<-c("xchangepoint","ychangepoint")
    list(max=max,changepoints=changepoints)
}