statsnakeblock<-function(img,istart,jstart,d=rep(0,times=32),dc=rep(1,times=32),locate=c(0,0,0,0)){
    row<-nrow(img)
    col<-ncol(img)
    if(locate[1]==0)
        locate[1]<-1
    if(locate[2]==0)
        locate[2]<-row
    if(locate[3]==0)
        locate[3]<-1
    if(locate[4]==0)
        locator[4]<-col
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\screening.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate1.R")
    source("D:\\R-3.0.1\\~My work place~\\snake\\Programs\\Tools\\calculate2.R")
    max<-0
    if(dc[1]==1)
    { 
     imax1<-0
     jmax1<-0
     imax11i<-0
     jmax11i<-0
     imax12i<-0
     jmax12i<-0
     max1<-0
     max2<-0
     s1<-0
     for(i in jstart:locate[4])    
          s1[i-jstart+1]<-img[istart,i]
     n<-length(s1)
     screening(n,s1)                                                                            
     O<-screening(n,s1)$O
     nO<-screening(n,s1)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s1,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s1,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax11i<-istart
      jmax11i<-jstart+O[cp1]-1
      max1<-NMCD[cp1]
     }
     if(d[1]!=1)
     {
      calculate2(s1,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s1,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax12i<-istart
      jmax12i<-jstart+O[cp1]-1
      imax12i[2]<-istart
      jmax12i[2]<-jstart+O[cp2]-1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[1]==1)
     {
      imax1<-imax11i
      jmax1<-jmax11i
      max<-max1
      points(jmax1,row-imax1,pch="。",col="red")
     }
     else if(d[1]==2)
     {
      imax1<-imax12i[1]
      jmax1<-jmax12i[1]
      imax1[2]<-imax12i[2]
      jmax1[2]<-jmax12i[2]
      max<-max2
      points(jmax1[1],row-imax1[1],pch="。",col="red")
      points(jmax1[2],row-imax1[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax1<-imax11i
       jmax1<-jmax11i
       max<-max1
       points(jmax1,row-imax1,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax1<-imax12i[1]
       jmax1<-jmax12i[1]
       imax1[2]<-imax12i[2]
       jmax1[2]<-jmax12i[2]
       max<-max2
       points(jmax1[1],row-imax1[1],pch="。",col="red")
       points(jmax1[2],row-imax1[2],pch="。",col="purple")
      }
     } 
    }
    
    if(dc[2]==1)
    { 
     imax2<-0
     jmax2<-0
     imax21i<-0
     jmax21i<-0
     imax22i<-0
     jmax22i<-0
     max1<-0
     max2<-0
     s2<-0
     i<-0
     while((istart+i<=locate[2])&&(jstart+2*i<=locate[4])){  
         s2[i+1]<-img[istart+i,jstart+2*i]
         i<-i+1
     }
     n<-length(s2)
     screening(n,s2)
     O<-screening(n,s2)$O
     nO<-screening(n,s2)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s2,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s2,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax21i<-istart+O[cp1]-1
      jmax21i<-jstart+2*O[cp1]-2
      max1<-NMCD[cp1]
     }
     if(d[2]!=1)
     {
      calculate2(s2,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s2,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax22i<-istart+O[cp1]-1
      jmax22i<-jstart+2*O[cp1]-2
      imax22i[2]<-istart+O[cp2]-1
      jmax22i[2]<-jstart+2*O[cp2]-2
      max2<-NMCD2[cp1,cp2]
     }
     if(d[2]==1)
     {
      imax2<-imax21i
      jmax2<-jmax21i
      max[2]<-max1
      points(jmax2,row-imax2,pch="。",col="red")
     }
     else if(d[2]==2)
     {
      imax2<-imax22i[1]
      jmax2<-jmax22i[1]
      imax2[2]<-imax22i[2]
      jmax2[2]<-jmax22i[2]
      max[2]<-max2
      points(jmax2[1],row-imax2[1],pch="。",col="red")
      points(jmax2[2],row-imax2[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax2<-imax21i
       jmax2<-jmax21i
       max[2]<-max1
       points(jmax2,row-imax2,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax2<-imax22i[1]
       jmax2<-jmax22i[1]
       imax2[2]<-imax22i[2]
       jmax2[2]<-jmax22i[2]
       max[2]<-max2
       points(jmax2[1],row-imax2[1],pch="。",col="red")
       points(jmax2[2],row-imax2[2],pch="。",col="purple")
      }
     } 
    }
    
    if(dc[3]==1)
    { 
     imax3<-0
     jmax3<-0
     imax31i<-0
     jmax31i<-0
     imax32i<-0
     jmax32i<-0
     max1<-0
     max2<-0
     s3<-0
     i<-0
     while((istart+i<=locate[2])&&(jstart+i<=locate[4])){  
         s3[i+1]<-img[istart+i,jstart+i]
         i<-i+1
     }
     n<-length(s3)
     screening(n,s3)
     O<-screening(n,s3)$O
     nO<-screening(n,s3)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s3,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s3,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax31i<-istart+O[cp1]-1
      jmax31i<-jstart+O[cp1]-1
      max1<-NMCD[cp1]
     }
     if(d[3]!=1)
     {
      calculate2(s3,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s3,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax32i<-istart+O[cp1]-1
      jmax32i<-jstart+O[cp1]-1
      imax32i[2]<-istart+O[cp2]-1
      jmax32i[2]<-jstart+O[cp2]-1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[3]==1)
     {
      imax3<-imax31i
      jmax3<-jmax31i
      max[3]<-max1
      points(jmax3,row-imax3,pch="。",col="red")
     }
     else if(d[3]==2)
     {
      imax3<-imax32i[1]
      jmax3<-jmax32i[1]
      imax3[2]<-imax32i[2]
      jmax3[2]<-jmax32i[2]
      max[3]<-max2
      points(jmax3[1],row-imax3[1],pch="。",col="red")
      points(jmax3[2],row-imax3[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax3<-imax31i
       jmax3<-jmax31i
       max[3]<-max1
       points(jmax3,row-imax3,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax3<-imax32i[1]
       jmax3<-jmax32i[1]
       imax3[2]<-imax32i[2]
       jmax3[2]<-jmax32i[2]
       max[3]<-max2
       points(jmax3[1],row-imax3[1],pch="。",col="red")
       points(jmax3[2],row-imax3[2],pch="。",col="purple")
      }
     } 
    }
    
    if(dc[4]==1)
    { 
     imax4<-0
     jmax4<-0
     imax41i<-0
     jmax41i<-0
     imax42i<-0
     jmax42i<-0
     max1<-0
     max2<-0
     s4<-0
     i<-0
     while((istart+2*i<=locate[2])&&(jstart+i<=locate[4])){  
         s4[i+1]<-img[istart+2*i,jstart+i]
         i<-i+1
     }
     n<-length(s4)
     screening(n,s4)
     O<-screening(n,s4)$O
     nO<-screening(n,s4)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s4,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s4,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax41i<-istart+2*O[cp1]-2
      jmax41i<-jstart+O[cp1]-1
      max1<-NMCD[cp1]
     }
     if(d[4]!=1)
     {
      calculate2(s4,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s4,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax42i<-istart+2*O[cp1]-2
      jmax42i<-jstart+O[cp1]-1
      imax42i[2]<-istart+2*O[cp2]-2
      jmax42i[2]<-jstart+O[cp2]-1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[4]==1)
     {
      imax4<-imax41i
      jmax4<-jmax41i
      max[4]<-max1
      points(jmax4,row-imax4,pch="。",col="red")
     }
     else if(d[4]==2)
     {
      imax4<-imax42i[1]
      jmax4<-jmax42i[1]
      imax4[2]<-imax42i[2]
      jmax4[2]<-jmax42i[2]
      max[4]<-max2
      points(jmax4[1],row-imax4[1],pch="。",col="red")
      points(jmax4[2],row-imax4[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax4<-imax41i
       jmax4<-jmax41i
       max[4]<-max1
       points(jmax4,row-imax4,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax4<-imax42i[1]
       jmax4<-jmax42i[1]
       imax4[2]<-imax42i[2]
       jmax4[2]<-jmax42i[2]
       max[4]<-max2
       points(jmax4[1],row-imax4[1],pch="。",col="red")
       points(jmax4[2],row-imax4[2],pch="。",col="purple")
      }
     } 
    }
    
    if(dc[5]==1)
    { 
     imax5<-0
     jmax5<-0
     imax51i<-0
     jmax51i<-0
     imax52i<-0
     jmax52i<-0
     max1<-0
     max2<-0
     s5<-0
     for(i in istart:locate[2])
         s5[i-istart+1]<-img[i,jstart]
     n<-length(s5)
     screening(n,s5)
     O<-0
     O<-screening(n,s5)$O
     nO<-screening(n,s5)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s5,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s5,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax51i<-istart+O[cp1]-1
      jmax51i<-jstart
      max1<-NMCD[cp1]
     }
     if(d[5]!=1)
     {
      calculate2(s5,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s5,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax52i<-istart+O[cp1]-1
      jmax52i<-jstart
      imax52i[2]<-istart+O[cp2]-1
      jmax52i[2]<-jstart
      max2<-NMCD2[cp1,cp2]
     }
     if(d[5]==1)
     {
      imax5<-imax51i
      jmax5<-jmax51i
      max[5]<-max1
      points(jmax5,row-imax5,pch="。",col="red")
     }
     else if(d[5]==2)
     {
      imax5<-imax52i[1]
      jmax5<-jmax52i[1]
      imax5[2]<-imax52i[2]
      jmax5[2]<-jmax52i[2]
      max[5]<-max2
      points(jmax5[1],row-imax5[1],pch="。",col="red")
      points(jmax5[2],row-imax5[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax5<-imax51i
       jmax5<-jmax51i
       max[5]<-max1
       points(jmax5,row-imax5,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax5<-imax52i[1]
       jmax5<-jmax52i[1]
       imax5[2]<-imax52i[2]
       jmax5[2]<-jmax52i[2]
       max[5]<-max2
       points(jmax5[1],row-imax5[1],pch="。",col="red")
       points(jmax5[2],row-imax5[2],pch="。",col="purple")
      }
     } 
    }
   
    if(dc[6]==1)
    { 
     imax6<-0
     jmax6<-0
     imax61i<-0
     jmax61i<-0
     imax62i<-0
     jmax62i<-0
     max1<-0
     max2<-0
     s6<-0
     i<-0
     while((istart+2*i<=locate[2])&&(jstart-i>=locate[3])){  
         s6[i+1]<-img[istart+2*i,jstart-i]
         i<-i+1
     }
     n<-length(s6)
     screening(n,s6)
     O<-0
     O<-screening(n,s6)$O
     nO<-screening(n,s6)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s6,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s6,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax61i<-istart+2*O[cp1]-2
      jmax61i<-jstart-O[cp1]+1
      max1<-NMCD[cp1]
     }
     if(d[6]!=1)
     {
      calculate2(s6,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s6,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax62i<-istart+2*O[cp1]-2
      jmax62i<-jstart-O[cp1]+1
      imax62i[2]<-istart+2*O[cp2]-2
      jmax62i[2]<-jstart-O[cp2]+1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[6]==1)
     {
      imax6<-imax31i
      jmax6<-jmax31i
      max[6]<-max1
      points(jmax6,row-imax6,pch="。",col="red")
     }
     else if(d[6]==2)
     {
      imax6<-imax62i[1]
      jmax6<-jmax62i[1]
      imax6[2]<-imax62i[2]
      jmax6[2]<-jmax62i[2]
      max[6]<-max2
      points(jmax6[1],row-imax6[1],pch="。",col="red")
      points(jmax6[2],row-imax6[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax6<-imax31i
       jmax6<-jmax31i
       max[6]<-max1
       points(jmax6,row-imax6,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax6<-imax62i[1]
       jmax6<-jmax62i[1]
       imax6[2]<-imax62i[2]
       jmax6[2]<-jmax62i[2]
       max[6]<-max2
       points(jmax6[1],row-imax6[1],pch="。",col="red")
       points(jmax6[2],row-imax6[2],pch="。",col="purple")
      }
     } 
    }
    
    if(dc[7]==1)
    { 
     imax7<-0
     jmax7<-0
     imax71i<-0
     jmax71i<-0
     imax72i<-0
     jmax72i<-0
     max1<-0
     max2<-0
     s7<-0
     i<-0
     while((istart+i<=locate[2])&&(jstart-i>=locate[3])){  
         s7[i+1]<-img[istart+i,jstart-i]
         i<-i+1
     }
     n<-length(s7)
     screening(n,s7)
     O<-0
     O<-screening(n,s7)$O
     nO<-screening(n,s7)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s7,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s7,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax71i<-istart+O[cp1]-1
      jmax71i<-jstart-O[cp1]+1
      max1<-NMCD[cp1]
     }
     if(d[7]!=1)
     {
      calculate2(s7,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s7,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax72i<-istart+O[cp1]-1
      jmax72i<-jstart-O[cp1]+1
      imax72i[2]<-istart+O[cp2]-1
      jmax72i[2]<-jstart-O[cp2]+1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[7]==1)
     {
      imax7<-imax71i
      jmax7<-jmax71i
      max[7]<-max1
      points(jmax7,row-imax7,pch="。",col="red")
     }
     else if(d[7]==2)
     {
      imax7<-imax72i[1]
      jmax7<-jmax72i[1]
      imax7[2]<-imax72i[2]
      jmax7[2]<-jmax72i[2]
      max[7]<-max2
      points(jmax7[1],row-imax7[1],pch="。",col="red")
      points(jmax7[2],row-imax7[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax7<-imax71i
       jmax7<-jmax71i
       max[7]<-max1
       points(jmax7,row-imax7,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax7<-imax72i[1]
       jmax7<-jmax72i[1]
       imax7[2]<-imax72i[2]
       jmax7[2]<-jmax72i[2]
       max[7]<-max2
       points(jmax7[1],row-imax7[1],pch="。",col="red")
       points(jmax7[2],row-imax7[2],pch="。",col="purple")
      }
     } 
    }
   
    if(dc[8]==1)
    { 
     imax8<-0
     jmax8<-0
     imax81i<-0
     jmax81i<-0
     imax82i<-0
     jmax82i<-0
     max1<-0
     max2<-0
     s8<-0
     i<-0
     while((istart+i<=locate[2])&&(jstart-2*i>=locate[3])){  
         s8[i+1]<-img[istart+i,jstart-2*i]
         i<-i+1
     }
     n<-length(s8)
     screening(n,s8)
     O<-0
     O<-screening(n,s8)$O
     nO<-screening(n,s8)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s8,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s8,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax81i<-istart+O[cp1]-1
      jmax81i<-jstart-2*O[cp1]+2
      max1<-NMCD[cp1]
     }
     if(d[8]!=1)
     {
      calculate2(s8,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s8,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax82i<-istart+O[cp1]-1
      jmax82i<-jstart-2*O[cp1]+2
      imax82i[2]<-istart+O[cp2]-1
      jmax82i[2]<-jstart-2*O[cp2]+2
      max2<-NMCD2[cp1,cp2]
     }
     if(d[8]==1)
     {
      imax8<-imax81i
      jmax8<-jmax81i
      max[8]<-max1
      points(jmax8,row-imax8,pch="。",col="red")
     }
     else if(d[8]==2)
     {
      imax8<-imax82i[1]
      jmax8<-jmax82i[1]
      imax8[2]<-imax82i[2]
      jmax8[2]<-jmax82i[2]
      max[8]<-max2
      points(jmax8[1],row-imax8[1],pch="。",col="red")
      points(jmax8[2],row-imax8[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax8<-imax81i
       jmax8<-jmax81i 
       max[8]<-max1
       points(jmax8,row-imax8,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax8<-imax82i[1]
       jmax8<-jmax82i[1]
       imax8[2]<-imax82i[2]
       jmax8[2]<-jmax82i[2]
       max[8]<-max2
       points(jmax8[1],row-imax8[1],pch="。",col="red")
       points(jmax8[2],row-imax8[2],pch="。",col="purple")
      }
     } 
    }
    
    if(dc[9]==1)
    { 
     imax9<-0
     jmax9<-0
     imax91i<-0
     jmax91i<-0
     imax92i<-0
     jmax92i<-0
     max1<-0
     max2<-0
     s9<-0
     for(i in 1:(jstart-locate[3]+1))
         s9[i]<-img[istart,jstart-i+1]
     n<-length(s9)
     screening(n,s9)
     O<-0
     O<-screening(n,s9)$O
     nO<-screening(n,s9)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s9,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s9,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax91i<-istart
      jmax91i<-jstart-O[cp1]+1
      max1<-NMCD[cp1]
     }
     if(d[9]!=1)
     {
      calculate2(s9,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s9,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax92i<-istart
      jmax92i<-jstart-O[cp1]+1
      imax92i[2]<-istart
      jmax92i[2]<-jstart-O[cp2]+1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[9]==1)
     {
      imax9<-imax91i
      jmax9<-jmax91i
      max[9]<-max1
      points(jmax9,row-imax9,pch="。",col="red")
     }
     else if(d[9]==2)
     {
      imax9<-imax92i[1]
      jmax9<-jmax92i[1]
      imax9[2]<-imax92i[2]
      jmax9[2]<-jmax92i[2]
      max[9]<-max2
      points(jmax9[1],row-imax9[1],pch="。",col="red")
      points(jmax9[2],row-imax9[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax9<-imax91i
       jmax9<-jmax91i
       max[9]<-max1
       points(jmax9,row-imax9,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax9<-imax92i[1]
       jmax9<-jmax92i[1]
       imax9[2]<-imax92i[2]
       jmax9[2]<-jmax92i[2]
       max[9]<-max2
       points(jmax9[1],row-imax9[1],pch="。",col="red")
       points(jmax9[2],row-imax9[2],pch="。",col="purple")
      }
     } 
    }
    
    if(dc[10]==1)
    { 
     imax10<-0
     jmax10<-0
     imax101i<-0
     jmax101i<-0
     imax102i<-0
     jmax102i<-0
     max1<-0
     max2<-0
     s10<-0 
     i<-0
     while((istart-i>=locate[1])&&(jstart-2*i>=locate[3])){  
         s10[i+1]<-img[istart-i,jstart-2*i]
         i<-i+1
     }
     n<-length(s10)
     screening(n,s10)
     O<-0
     O<-screening(n,s10)$O
     nO<-screening(n,s10)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s10,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s10,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax101i<-istart-O[cp1]+1
      jmax101i<-jstart-2*O[cp1]+2
      max1<-NMCD[cp1]
     }
     if(d[10]!=1)
     {
      calculate2(s10,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s10,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax102i<-istart-O[cp1]+1
      jmax102i<-jstart-2*O[cp1]+2
      imax102i[2]<-istart-O[cp2]+1
      jmax102i[2]<-jstart-2*O[cp2]+2
      max2<-NMCD2[cp1,cp2]
     }
     if(d[10]==1)
     {
      imax10<-imax101i
      jmax10<-jmax101i
      max[10]<-max1
      points(jmax10,row-imax10,pch="。",col="red")
     }
     else if(d[10]==2)
     {
      imax10<-imax102i[1]
      jmax10<-jmax102i[1]
      imax10[2]<-imax102i[2]
      jmax10[2]<-jmax102i[2]
      max[10]<-max2
      points(jmax10[1],row-imax10[1],pch="。",col="red")
      points(jmax10[2],row-imax10[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax10<-imax101i
       jmax10<-jmax101i
       max[10]<-max1
       points(jmax10,row-imax10,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax10<-imax102i[1]
       jmax10<-jmax102i[1]
       imax10[2]<-imax102i[2]
       jmax10[2]<-jmax102i[2]
       max[10]<-max2
       points(jmax10[1],row-imax10[1],pch="。",col="red")
       points(jmax10[2],row-imax10[2],pch="。",col="purple")
      }
     } 
    }
    
    if(dc[11]==1)
    { 
     imax11<-0
     jmax11<-0
     imax111i<-0
     jmax111i<-0
     imax112i<-0
     jmax112i<-0
     max1<-0
     max2<-0
     s11<-0
     i<-0
     while((istart-i>=locate[1])&&(jstart-i>=locate[3])){  
         s11[i+1]<-img[istart-i,jstart-i]
         i<-i+1
     }
     n<-length(s11)
     screening(n,s11)
     O<-0
     O<-screening(n,s11)$O
     nO<-screening(n,s11)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s11,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s11,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax111i<-istart-O[cp1]+1
      jmax111i<-jstart-O[cp1]+1
      max1<-NMCD[cp1]
     }
     if(d[11]!=1)
     {
      calculate2(s11,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s11,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax112i<-istart-O[cp1]+1
      jmax112i<-jstart-O[cp1]+1
      imax112i[2]<-istart-O[cp2]+1
      jmax112i[2]<-jstart-O[cp2]+1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[11]==1)
     {
      imax11<-imax111i
      jmax11<-jmax111i
      max[11]<-max1
      points(jmax11,row-imax11,pch="。",col="red")
     }
     else if(d[11]==2)
     {
      imax11<-imax112i[1]
      jmax11<-jmax112i[1]
      imax11[2]<-imax112i[2]
      jmax11[2]<-jmax112i[2]
      max[11]<-max2
      points(jmax11[1],row-imax11[1],pch="。",col="red")
      points(jmax11[2],row-imax11[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax11<-imax111i
       jmax11<-jmax111i
       max[11]<-max1
       points(jmax11,row-imax11,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax11<-imax112i[1]
       jmax11<-jmax112i[1]
       imax11[2]<-imax112i[2]
       jmax11[2]<-jmax112i[2]
       max[11]<-max2
       points(jmax11[1],row-imax11[1],pch="。",col="red")
       points(jmax11[2],row-imax11[2],pch="。",col="purple")
      }
     } 
    }
  
    if(dc[12]==1)
    { 
     imax12<-0
     jmax12<-0
     imax121i<-0
     jmax121i<-0
     imax122i<-0
     jmax122i<-0
     max1<-0
     max2<-0
     s12<-0
     i<-0
     while((istart-2*i>=locate[1])&&(jstart-i>=locate[3])){  
         s12[i+1]<-img[istart-2*i,jstart-i]
         i<-i+1
     }
     n<-length(s12)
     screening(n,s12)
     O<-0
     O<-screening(n,s12)$O
     nO<-screening(n,s12)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s12,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s12,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax121i<-istart-2*O[cp1]+2
      jmax121i<-jstart-O[cp1]+1
      max1<-NMCD[cp1]
     }
     if(d[12]!=1)
     {
      calculate2(s12,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s12,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax122i<-istart-O[cp1]+2
      jmax122i<-jstart-O[cp1]+1
      imax122i[2]<-istart-2*O[cp2]+2
      jmax122i[2]<-jstart-O[cp2]+1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[12]==1)
     {
      imax12<-imax121i
      jmax12<-jmax121i
      max[12]<-max1
      points(jmax12,row-imax12,pch="。",col="red")
     }
     else if(d[12]==2)
     {
      imax12<-imax122i[1]
      jmax12<-jmax122i[1]
      imax12[2]<-imax122i[2]
      jmax12[2]<-jmax122i[2]
      max[12]<-max2
      points(jmax12[1],row-imax12[1],pch="。",col="red")
      points(jmax12[2],row-imax12[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax12<-imax121i
       jmax12<-jmax121i
       max[12]<-max1
       points(jmax12,row-imax12,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax12<-imax122i[1]
       jmax12<-jmax122i[1]
       imax12[2]<-imax122i[2]
       jmax12[2]<-jmax122i[2]
       max[12]<-max2
       points(jmax12[1],row-imax12[1],pch="。",col="red")
       points(jmax12[2],row-imax12[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[13]==1)
    { 
     imax13<-0
     jmax13<-0
     imax131i<-0
     jmax131i<-0
     imax132i<-0
     jmax132i<-0
     max1<-0
     max2<-0
     s13<-0
     for(i in 1:(istart-locate[1]+1))
         s13[i]<-img[istart-i+1,jstart]
     n<-length(s13)
     screening(n,s13)
     O<-0
     O<-screening(n,s13)$O
     nO<-screening(n,s13)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s13,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s13,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax131i<-istart-O[cp1]+1
      jmax131i<-jstart
      max1<-NMCD[cp1]
     }
     if(d[13]!=1)
     {
      calculate2(s13,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s13,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax132i<-istart-O[cp1]+1
      jmax132i<-jstart
      imax132i[2]<-istart-O[cp2]+1
      jmax132i[2]<-jstart
      max2<-NMCD2[cp1,cp2]
     }
     if(d[13]==1)
     {
      imax13<-imax131i
      jmax13<-jmax131i
      max[13]<-max1
      points(jmax13,row-imax13,pch="。",col="red")
     }
     else if(d[13]==2)
     {
      imax13<-imax132i[1]
      jmax13<-jmax132i[1]
      imax13[2]<-imax132i[2]
      jmax13[2]<-jmax132i[2]
      max[13]<-max2
      points(jmax13[1],row-imax13[1],pch="。",col="red")
      points(jmax13[2],row-imax13[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax13<-imax131i
       jmax13<-jmax131i
       max[13]<-max1
       points(jmax13,row-imax13,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax13<-imax132i[1]
       jmax13<-jmax132i[1]
       imax13[2]<-imax132i[2]
       jmax13[2]<-jmax132i[2]
       max[13]<-max2
       points(jmax13[1],row-imax13[1],pch="。",col="red")
       points(jmax13[2],row-imax13[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[14]==1)
    { 
     imax14<-0
     jmax14<-0
     imax141i<-0
     jmax141i<-0
     imax142i<-0
     jmax142i<-0
     max1<-0
     max2<-0
     s14<-0                                                                               #The 14th direnction
     i<-0
     while((istart-2*i>=locate[1])&&(jstart+i<=locate[4])){  
         s14[i+1]<-img[istart-2*i,jstart+i]
         i<-i+1
     }
     n<-length(s14)
     screening(n,s14)
     O<-0
     O<-screening(n,s14)$O
     nO<-screening(n,s14)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s14,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s14,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax141i<-istart-2*O[cp1]+2
      jmax141i<-jstart+O[cp1]-1
      max1<-NMCD[cp1]
     }
     if(d[14]!=1)
     {
      calculate2(s14,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s14,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax142i<-istart-2*O[cp1]+2
      jmax142i<-jstart+O[cp1]-1
      imax142i[2]<-istart-2*O[cp2]+2
      jmax142i[2]<-jstart+O[cp2]-1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[14]==1)
     {
      imax14<-imax31i
      jmax14<-jmax31i
      max[14]<-max1
      points(jmax14,row-imax14,pch="。",col="red")
     }
     else if(d[14]==2)
     {
      imax14<-imax142i[1]
      jmax14<-jmax142i[1]
      imax14[2]<-imax142i[2]
      jmax14[2]<-jmax142i[2]
      max[14]<-max2
      points(jmax14[1],row-imax14[1],pch="。",col="red")
      points(jmax14[2],row-imax14[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax14<-imax141i
       jmax14<-jmax141i
       max[14]<-max1
       points(jmax14,row-imax14,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax14<-imax142i[1]
       jmax14<-jmax142i[1]
       imax14[2]<-imax142i[2]
       jmax14[2]<-jmax142i[2]
       max[14]<-max2
       points(jmax14[1],row-imax14[1],pch="。",col="red")
       points(jmax14[2],row-imax14[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[15]==1)
    { 
     imax15<-0
     jmax15<-0
     imax151i<-0
     jmax151i<-0
     imax152i<-0
     jmax152i<-0
     max1<-0
     max2<-0
     s15<-0
     i<-0
     while((istart-i>=locate[1])&&(jstart+i<=locate[4])){  
         s15[i+1]<-img[istart-i,jstart+i]
         i<-i+1
     }
     n<-length(s15)
     screening(n,s15)
     O<-0
     O<-screening(n,s15)$O
     nO<-screening(n,s15)$nO

     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s15,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s15,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax151i<-istart-O[cp1]+1
      jmax151i<-jstart+O[cp1]-1
      max1<-NMCD[cp1]
     }
     if(d[15]!=1)
     {
      calculate2(s15,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s15,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax152i<-istart-O[cp1]+1
      jmax152i<-jstart+O[cp1]-1
      imax152i[2]<-istart-O[cp2]+1
      jmax152i[2]<-jstart+O[cp2]-1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[15]==1)
     {
      imax15<-imax151i
      jmax15<-jmax151i
      max[15]<-max1
      points(jmax15,row-imax15,pch="。",col="red")
     }
     else if(d[15]==2)
     {
      imax15<-imax152i[1]
      jmax15<-jmax152i[1]
      imax15[2]<-imax152i[2]
      jmax15[2]<-jmax152i[2]
      max[15]<-max2
      points(jmax15[1],row-imax15[1],pch="。",col="red")
      points(jmax15[2],row-imax15[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax15<-imax151i
       jmax15<-jmax151i
       max[15]<-max1
       points(jmax15,row-imax15,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax15<-imax152i[1]
       jmax15<-jmax32i[1]
       imax15[2]<-imax32i[2]
       jmax15[2]<-jmax32i[2]
       max[15]<-max2
       points(jmax15[1],row-imax15[1],pch="。",col="red")
       points(jmax15[2],row-imax15[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[16]==1)
    { 
     imax16<-0
     jmax16<-0
     imax161i<-0
     jmax161i<-0
     imax162i<-0
     jmax162i<-0
     max1<-0
     max2<-0
     s16<-0
     i<-0
     while((istart-i>=locate[1])&&(jstart+2*i<=locate[4])){  
         s16[i+1]<-img[istart-i,jstart+2*i]
         i<-i+1
     }
     n<-length(s16)
     screening(n,s16)
     O<-0
     O<-screening(n,s16)$O
     nO<-screening(n,s16)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s16,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s16,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax161i<-istart-O[cp1]+1
      jmax161i<-jstart+2*O[cp1]-2
      max1<-NMCD[cp1]
     }
     if(d[16]!=1)
     {
      calculate2(s16,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s16,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax162i<-istart-O[cp1]+1
      jmax162i<-jstart+2*O[cp1]-2
      imax162i[2]<-istart-O[cp2]+1
      jmax162i[2]<-jstart+2*O[cp2]-2
      max2<-NMCD2[cp1,cp2]
     }
     if(d[16]==1)
     {
      imax16<-imax161i
      jmax16<-jmax161i
      max[16]<-max1
      points(jmax16,row-imax16,pch="。",col="red")
     }
     else if(d[16]==2)
     {
      imax16<-imax162i[1]
      jmax16<-jmax162i[1]
      imax16[2]<-imax162i[2]
      jmax16[2]<-jmax162i[2]
      max[16]<-max2
      points(jmax16[1],row-imax16[1],pch="。",col="red")
      points(jmax16[2],row-imax16[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax16<-imax161i
       jmax16<-jmax161i
       max[16]<-max1
       points(jmax16,row-imax16,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax16<-imax162i[1]
       jmax16<-jmax162i[1]
       imax16[2]<-imax162i[2]
       jmax16[2]<-jmax162i[2]
       max[16]<-max2
       points(jmax16[1],row-imax16[1],pch="。",col="red")
       points(jmax16[2],row-imax16[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[17]==1)
    { 
     imax17<-0
     jmax17<-0
     imax171i<-0
     jmax171i<-0
     imax172i<-0
     jmax172i<-0
     max1<-0
     max2<-0
     s17<-0
     i<-0
     while((istart+i<=locate[2])&&(jstart+3*i<=locate[4])){  
         s17[i+1]<-img[istart+i,jstart+3*i]
         i<-i+1
     }
     n<-length(s17)
     screening(n,s17)
     O<-0
     O<-screening(n,s17)$O
     nO<-screening(n,s17)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s17,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s17,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax171i<-istart+O[cp1]-1
      jmax171i<-jstart+3*O[cp1]-3
      max1<-NMCD[cp1]
     }
     if(d[17]!=1)
     {
      calculate2(s17,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s17,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax172i<-istart+O[cp1]-1
      jmax172i<-jstart+3*O[cp1]-3
      imax172i[2]<-istart+O[cp2]-1
      jmax172i[2]<-jstart+3*O[cp2]-3
      max2<-NMCD2[cp1,cp2]
     }
     if(d[17]==1)
     {
      imax17<-imax171i
      jmax17<-jmax171i
      max[17]<-max1
      points(jmax17,row-imax17,pch="。",col="red")
     }
     else if(d[17]==2)
     {
      imax17<-imax172i[1]
      jmax17<-jmax172i[1]
      imax17[2]<-imax172i[2]
      jmax17[2]<-jmax172i[2]
      max[17]<-max2
      points(jmax17[1],row-imax17[1],pch="。",col="red")
      points(jmax17[2],row-imax17[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax17<-imax171i
       jmax17<-jmax171i
       max[17]<-max1
       points(jmax17,row-imax17,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax17<-imax172i[1]
       jmax17<-jmax172i[1]
       imax17[2]<-imax172i[2]
       jmax17[2]<-jmax172i[2]
       max[17]<-max2
       points(jmax17[1],row-imax17[1],pch="。",col="red")
       points(jmax17[2],row-imax17[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[18]==1)
    { 
     imax18<-0
     jmax18<-0
     imax181i<-0
     jmax181i<-0
     imax182i<-0
     jmax182i<-0
     max1<-0
     max2<-0
     s18<-0
     i<-0
     while((istart+2*i<=locate[2])&&(jstart+3*i<=locate[4])){  
             s18[i+1]<-img[istart+2*i,jstart+3*i]
             i<-i+1
     }
     n<-length(s18)
     screening(n,s18)
     O<-0
     O<-screening(n,s18)$O
     nO<-screening(n,s18)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s18,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s18,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax181i<-istart+2*O[cp1]-2
      jmax181i<-jstart+3*O[cp1]-3
      max1<-NMCD[cp1]
     }
     if(d[18]!=1)
     {
      calculate2(s18,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s18,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax182i<-istart+2*O[cp1]-2
      jmax182i<-jstart+3*O[cp1]-3
      imax182i[2]<-istart+2*O[cp2]-2
      jmax182i[2]<-jstart+3*O[cp2]-3
      max2<-NMCD2[cp1,cp2]
     }
     if(d[3]==1)
     {
      imax18<-imax181i
      jmax18<-jmax181i
      max[18]<-max1
      points(jmax18,row-imax18,pch="。",col="red")
     }
     else if(d[18]==2)
     {
      imax18<-imax182i[1]
      jmax18<-jmax182i[1]
      imax18[2]<-imax182i[2]
      jmax18[2]<-jmax182i[2]
      max[18]<-max2
      points(jmax18[1],row-imax18[1],pch="。",col="red")
      points(jmax18[2],row-imax18[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax18<-imax181i
       jmax18<-jmax181i
       max[18]<-max1
       points(jmax18,row-imax18,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax18<-imax182i[1]
       jmax18<-jmax32i[1]
       imax18[2]<-imax182i[2]
       jmax18[2]<-jmax182i[2]
       max[18]<-max2
       points(jmax18[1],row-imax18[1],pch="。",col="red")
       points(jmax18[2],row-imax18[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[19]==1)
    { 
     imax19<-0
     jmax19<-0
     imax191i<-0
     jmax191i<-0
     imax192i<-0
     jmax192i<-0
     max1<-0
     max2<-0
     s19<-0
     i<-0
     while((istart+3*i<=locate[2])&&(jstart+2*i<=locate[4])){  
             s19[i+1]<-img[istart+3*i,jstart+2*i]
             i<-i+1
     }
     n<-length(s19)
     screening(n,s19)
     O<-0
     O<-screening(n,s19)$O
     nO<-screening(n,s19)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s19,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s19,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax191i<-istart+3*O[cp1]-3
      jmax191i<-jstart+2*O[cp1]-2
      max1<-NMCD[cp1]
     }
     if(d[19]!=1)
     {
      calculate2(s19,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s19,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax192i<-istart+3*O[cp1]-3
      jmax192i<-jstart+2*O[cp1]-2
      imax192i[2]<-istart+3*O[cp2]-3
      jmax192i[2]<-jstart+2*O[cp2]-2
      max2<-NMCD2[cp1,cp2]
     }
     if(d[19]==1)
     {
      imax19<-imax191i
      jmax19<-jmax191i
      max[19]<-max1
      points(jmax19,row-imax19,pch="。",col="red")
     }
     else if(d[19]==2)
     {
      imax19<-imax192i[1]
      jmax19<-jmax192i[1]
      imax19[2]<-imax192i[2]
      jmax19[2]<-jmax192i[2]
      max[19]<-max2
      points(jmax19[1],row-imax19[1],pch="。",col="red")
      points(jmax19[2],row-imax19[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax19<-imax191i
       jmax19<-jmax191i
       max[19]<-max1
       points(jmax19,row-imax19,pch="。",col="red")
      }
      else if(min==(-max2+2*zeta))
      {
       imax19<-imax192i[1]
       jmax19<-jmax192i[1]
       imax19[2]<-imax192i[2]
       jmax19[2]<-jmax192i[2]
       max[19]<-max2
       points(jmax19[1],row-imax19[1],pch="。",col="red")
       points(jmax19[2],row-imax19[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[20]==1)
    { 
     imax20<-0
     jmax20<-0
     imax201i<-0
     jmax201i<-0
     imax202i<-0
     jmax202i<-0
     max1<-0
     max2<-0
     s20<-0
     i<-0
     while((istart+3*i<=locate[2])&&(jstart+i<=locate[4])){  
         s20[i+1]<-img[istart+3*i,jstart+i]
         i<-i+1
     }
     n<-length(s20)
     screening(n,s20)
     O<-0
     O<-screening(n,s20)$O
     nO<-screening(n,s20)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s20,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s20,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax201i<-istart+3*O[cp1]-3
      jmax201i<-jstart+O[cp1]-1
      max1<-NMCD[cp1]
     }
     if(d[20]!=1)
     {
      calculate2(s20,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s20,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax202i<-istart+3*O[cp1]-3
      jmax202i<-jstart+O[cp1]-1
      imax202i[2]<-istart+3*O[cp2]-3
      jmax202i[2]<-jstart+O[cp2]-1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[20]==1)
     {
      imax20<-imax201i
      jmax20<-jmax201i
      max[20]<-max1
      points(jmax20,row-imax20,pch="。",col="red")
     }
     else if(d[20]==2)
     {
      imax20<-imax202i[1]
      jmax20<-jmax202i[1]
      imax20[2]<-imax202i[2]
      jmax20[2]<-jmax202i[2]
      max[20]<-max2
      points(jmax20[1],row-imax20[1],pch="。",col="red")
      points(jmax20[2],row-imax20[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax20<-imax201i
       jmax20<-jmax201i
       max[20]<-max1
       points(jmax20,row-imax20,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax20<-imax202i[1]
       jmax20<-jmax202i[1]
       imax20[2]<-imax202i[2]
       jmax20[2]<-jmax202i[2]
       max[20]<-max2
       points(jmax20[1],row-imax20[1],pch="。",col="red")
       points(jmax20[2],row-imax20[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[21]==1)
    { 
     imax21<-0
     jmax21<-0
     imax211i<-0
     jmax211i<-0
     imax212i<-0
     jmax212i<-0
     max1<-0
     max2<-0
     s21<-0
     i<-0
     while((istart+3*i<=locate[2])&&(jstart-i>=locate[3])){  
         s21[i+1]<-img[istart+3*i,jstart-i]
         i<-i+1
     }
     n<-length(s21)
     screening(n,s21)
     O<-0
     O<-screening(n,s21)$O
     nO<-screening(n,s21)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s21,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s21,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax211i<-istart+3*O[cp1]-3
      jmax211i<-jstart-O[cp1]+1
      max1<-NMCD[cp1]
     }
     if(d[21]!=1)
     {
      calculate2(s21,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s21,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax212i<-istart+3*O[cp1]-3
      jmax212i<-jstart-O[cp1]+1
      imax212i[2]<-istart+3*O[cp2]-3
      jmax212i[2]<-jstart-O[cp2]+1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[21]==1)
     {
      imax21<-imax211i
      jmax21<-jmax211i
      max[21]<-max1
      points(jmax21,row-imax21,pch="。",col="red")
     }
     else if(d[21]==2)
     {
      imax21<-imax212i[1]
      jmax21<-jmax212i[1]
      imax21[2]<-imax32i[2]
      jmax21[2]<-jmax32i[2]
      max[21]<-max2
      points(jmax21[1],row-imax21[1],pch="。",col="red")
      points(jmax21[2],row-imax21[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax21<-imax211i
       jmax21<-jmax211i
       max[21]<-max1
       points(jmax21,row-imax21,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax21<-imax212i[1]
       jmax21<-jmax212i[1]
       imax21[2]<-imax212i[2]
       jmax21[2]<-jmax212i[2]
       max[21]<-max2
       points(jmax21[1],row-imax21[1],pch="。",col="red")
       points(jmax21[2],row-imax21[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[22]==1)
    { 
     imax22<-0
     jmax22<-0
     imax221i<-0
     jmax221i<-0
     imax222i<-0
     jmax222i<-0
     max1<-0
     max2<-0
     s22<-0
     i<-0
     while((istart+3*i<=locate[2])&&(jstart-2*i>=locate[3])){  
             s22[i+1]<-img[istart+3*i,jstart-2*i]
             i<-i+1
     }
     n<-length(s22)
     screening(n,s22)
     O<-0
     O<-screening(n,s22)$O
     nO<-screening(n,s22)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s22,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s22,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax221i<-istart+3*O[cp1]-3
      jmax221i<-jstart-2*O[cp1]+2
      max1<-NMCD[cp1]
     }
     if(d[3]!=1)
     {
      calculate2(s22,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s22,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax222i<-istart+3*O[cp1]-3
      imax222i<-istart-2*O[cp1]+2
      imax222i[2]<-istart+3*O[cp2]-3
      jmax222i[2]<-jstart-2*O[cp2]+2
      max2<-NMCD2[cp1,cp2]
     }
     if(d[22]==1)
     {
      imax22<-imax221i
      jmax22<-jmax221i
      max[22]<-max1
      points(jmax22,row-imax22,pch="。",col="red")
     }
     else if(d[22]==2)
     {
      imax22<-imax222i[1]
      jmax22<-jmax222i[1]
      imax22[2]<-imax222i[2]
      jmax22[2]<-jmax222i[2]
      max[22]<-max2
      points(jmax22[1],row-imax22[1],pch="。",col="red")
      points(jmax22[2],row-imax22[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax22<-imax221i
       jmax22<-jmax221i
       max[22]<-max1
       points(jmax22,row-imax22,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax22<-imax222i[1]
       jmax22<-jmax222i[1]
       imax22[2]<-imax222i[2]
       jmax22[2]<-jmax222i[2]
       max[22]<-max2
       points(jmax22[1],row-imax22[1],pch="。",col="red")
       points(jmax22[2],row-imax22[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[23]==1)
    { 
     imax23<-0
     jmax23<-0
     imax231i<-0
     jmax231i<-0
     imax232i<-0
     jmax232i<-0
     max1<-0
     max2<-0
     s23<-0
     i<-0
     while((istart+2*i<=locate[2])&&(jstart-3*i>=locate[3])){  
             s23[i+1]<-img[istart+2*i,jstart-3*i]
             i<-i+1
     }
     n<-length(s23)
     screening(n,s23)
     O<-0
     O<-screening(n,s23)$O
     nO<-screening(n,s23)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s23,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s23,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax231i<-istart+2*O[cp1]-2
      jmax231i<-jstart-3*O[cp1]+3
      max1<-NMCD[cp1]
     }
     if(d[23]!=1)
     {
      calculate2(s23,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s23,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax232i<-istart+2*O[cp1]-2
      jmax232i<-jstart-3*O[cp1]+3
      imax232i[2]<-istart+2*O[cp2]-2
      jmax232i[2]<-jstart-3*O[cp2]+3
      max2<-NMCD2[cp1,cp2]
     }
     if(d[23]==1)
     {
      imax23<-imax31i
      jmax23<-jmax31i
      max[23]<-max1
      points(jmax3,row-imax3,pch="。",col="red")
     }
     else if(d[23]==2)
     {
      imax23<-imax232i[1]
      jmax23<-jmax232i[1]
      imax23[2]<-imax232i[2]
      jmax23[2]<-jmax232i[2]
      max[23]<-max2
      points(jmax23[1],row-imax23[1],pch="。",col="red")
      points(jmax23[2],row-imax23[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax23<-imax231i
       jmax23<-jmax231i
       max[23]<-max1
       points(jmax23,row-imax23,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax23<-imax232i[1]
       jmax23<-jmax232i[1]
       imax23[2]<-imax232i[2]
       jmax23[2]<-jmax232i[2]
       max[3]<-max2
       points(jmax23[1],row-imax23[1],pch="。",col="red")
       points(jmax23[2],row-imax23[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[24]==1)
    { 
     imax24<-0
     jmax24<-0
     imax241i<-0
     jmax241i<-0
     imax242i<-0
     jmax242i<-0
     max1<-0
     max2<-0
     s24<-0
     i<-0
     while((istart+i<=locate[2])&&(jstart-3*i>=locate[3])){  
         s24[i+1]<-img[istart+i,jstart-3*i]
         i<-i+1
     }
     n<-length(s24)
     screening(n,s24)
     O<-0
     O<-screening(n,s24)$O
     nO<-screening(n,s24)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s24,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s24,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax241i<-istart+O[cp1]-1
      jmax241i<-jstart-3*O[cp1]+3
      max1<-NMCD[cp1]
     }
     if(d[24]!=1)
     {
      calculate2(s3,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s3,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax242i<-istart+O[cp1]-1
      jmax242i<-jstart-3*O[cp1]+3
      imax242i[2]<-istart+O[cp2]-1
      jmax242i[2]<-jstart-3*O[cp2]+3
      max2<-NMCD2[cp1,cp2]
     }
     if(d[24]==1)
     {
      imax24<-imax31i
      jmax24<-jmax31i
      max[24]<-max1
      points(jmax24,row-imax24,pch="。",col="red")
     }
     else if(d[24]==2)
     {
      imax24<-imax242i[1]
      jmax24<-jmax242i[1]
      imax24[2]<-imax242i[2]
      jmax24[2]<-jmax242i[2]
      max[24]<-max2
      points(jmax24[1],row-imax24[1],pch="。",col="red")
      points(jmax24[2],row-imax24[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax24<-imax241i
       jmax24<-jmax241i
       max[24]<-max1
       points(jmax24,row-imax24,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax24<-imax242i[1]
       jmax24<-jmax242i[1]
       imax24[2]<-imax242i[2]
       jmax24[2]<-jmax242i[2]
       max[24]<-max2
       points(jmax24[1],row-imax24[1],pch="。",col="red")
       points(jmax24[2],row-imax24[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[25]==1)
    { 
     imax25<-0
     jmax25<-0
     imax251i<-0
     jmax251i<-0
     imax252i<-0
     jmax252i<-0
     max1<-0
     max2<-0
     s25<-0
     i<-0
     while((istart-i>=locate[1])&&(jstart-3*i>=locate[3])){  
         s25[i+1]<-img[istart-i,jstart-3*i]
         i<-i+1
     }
     n<-length(s25)
     screening(n,s25)
     O<-0
     O<-screening(n,s25)$O
     nO<-screening(n,s25)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s25,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s25,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax251i<-istart-O[cp1]+1
      jmax251i<-jstart-3*O[cp1]+3
      max1<-NMCD[cp1]
     }
     if(d[25]!=1)
     {
      calculate2(s25,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s25,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax252i<-istart-O[cp1]+1
      jmax252i<-jstart-3*O[cp1]+3
      imax252i[2]<-istart-O[cp2]+1
      jmax252i[2]<-jstart-3*O[cp2]+3
      max2<-NMCD2[cp1,cp2]
     }
     if(d[25]==1)
     {
      imax25<-imax251i
      jmax25<-jmax251i
      max[25]<-max1
      points(jmax25,row-imax25,pch="。",col="red")
     }
     else if(d[25]==2)
     {
      imax25<-imax252i[1]
      jmax25<-jmax252i[1]
      imax25[2]<-imax252i[2]
      jmax25[2]<-jmax252i[2]
      max[25]<-max2
      points(jmax25[1],row-imax25[1],pch="。",col="red")
      points(jmax25[2],row-imax25[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax25<-imax251i
       jmax25<-jmax251i
       max[25]<-max1
       points(jmax25,row-imax25,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax25<-imax252i[1]
       jmax25<-jmax252i[1]
       imax25[2]<-imax252i[2]
       jmax25[2]<-jmax252i[2]
       max[25]<-max2
       points(jmax25[1],row-imax25[1],pch="。",col="red")
       points(jmax25[2],row-imax25[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[26]==1)
    { 
     imax26<-0
     jmax26<-0
     imax261i<-0
     jmax261i<-0
     imax262i<-0
     jmax262i<-0
     max1<-0
     max2<-0
     s26<-0
     i<-0
     while((istart-2*i>=locate[1])&&(jstart-3*i>=locate[3])){  
             s26[i+1]<-img[istart-2*i,jstart-3*i]
             i<-i+1
     }
     n<-length(s26)
     screening(n,s26)
     O<-0
     O<-screening(n,s26)$O
     nO<-screening(n,s26)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s26,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s26,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax261i<-istart-2*O[cp1]+2
      jmax261i<-jstart-3*O[cp1]+3
      max1<-NMCD[cp1]
     }
     if(d[26]!=1)
     {
      calculate2(s26,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s26,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax262i<-istart-2*O[cp1]+2
      jmax262i<-jstart-3*O[cp1]+3
      imax262i[2]<-istart-2*O[cp2]+2
      jmax262i[2]<-jstart-3*O[cp2]+3
      max2<-NMCD2[cp1,cp2]
     }
     if(d[26]==1)
     {
      imax26<-imax261i
      jmax26<-jmax261i
      max[26]<-max1
      points(jmax26,row-imax26,pch="。",col="red")
     }
     else if(d[26]==2)
     {
      imax26<-imax262i[1]
      jmax26<-jmax262i[1]
      imax26[2]<-imax262i[2]
      jmax26[2]<-jmax262i[2]
      max[26]<-max2
      points(jmax26[1],row-imax26[1],pch="。",col="red")
      points(jmax26[2],row-imax26[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax26<-imax261i
       jmax26<-jmax261i
       max[26]<-max1
       points(jmax26,row-imax26,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax26<-imax262i[1]
       jmax26<-jmax262i[1]
       imax26[2]<-imax262i[2]
       jmax26[2]<-jmax262i[2]
       max[26]<-max2
       points(jmax26[1],row-imax26[1],pch="。",col="red")
       points(jmax26[2],row-imax26[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[27]==1)
    { 
     imax27<-0
     jmax27<-0
     imax271i<-0
     jmax271i<-0
     imax272i<-0
     jmax272i<-0
     max1<-0
     max2<-0
     s27<-0
     i<-0
     while((istart-3*i>=locate[1])&&(jstart-2*i>=locate[3])){  
             s27[i+1]<-img[istart-3*i,jstart-2*i]
             i<-i+1
     }
     n<-length(s27)
     screening(n,s27)
     O<-0
     O<-screening(n,s27)$O
     nO<-screening(n,s27)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s27,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s27,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax271i<-istart-3*O[cp1]+3
      jmax271i<-jstart-2*O[cp1]+2
      max1<-NMCD[cp1]
     }
     if(d[27]!=1)
     {
      calculate2(s27,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s27,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax272i<-istart-3*O[cp1]+3
      jmax272i<-jstart-2*O[cp1]+2
      imax272i[2]<-istart-3*O[cp2]+3
      jmax272i[2]<-jstart-2*O[cp2]+2
      max2<-NMCD2[cp1,cp2]
     }
     if(d[27]==1)
     {
      imax27<-imax271i
      jmax27<-jmax271i
      max[27]<-max1
      points(jmax27,row-imax27,pch="。",col="red")
     }
     else if(d[27]==2)
     {
      imax27<-imax272i[1]
      jmax27<-jmax32i[1]
      imax27[2]<-imax272i[2]
      jmax27[2]<-jmax272i[2]
      max[27]<-max2
      points(jmax27[1],row-imax27[1],pch="。",col="red")
      points(jmax27[2],row-imax27[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax27<-imax271i
       jmax27<-jmax271i
       max[27]<-max1
       points(jmax27,row-imax27,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax27<-imax272i[1]
       jmax27<-jmax272i[1]
       imax27[2]<-imax272i[2]
       jmax27[2]<-jmax272i[2]
       max[27]<-max2
       points(jmax27[1],row-imax27[1],pch="。",col="red")
       points(jmax27[2],row-imax27[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[28]==1)
    { 
     imax28<-0
     jmax28<-0
     imax281i<-0
     jmax281i<-0
     imax282i<-0
     jmax282i<-0
     max1<-0
     max2<-0
     s28<-0
     i<-0
     while((istart-3*i>=locate[1])&&(jstart-i>=locate[3])){  
         s28[i+1]<-img[istart-3*i,jstart-i]
         i<-i+1
     }
     n<-length(s28)
     screening(n,s28)
     O<-0
     O<-screening(n,s28)$O
     nO<-screening(n,s28)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s28,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s28,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax281i<-istart-3*O[cp1]+3
      jmax281i<-jstart-O[cp1]+1
      max1<-NMCD[cp1]
     }
     if(d[28]!=1)
     {
      calculate2(s28,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s28,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax282i<-istart-3*O[cp1]+3
      jmax282i<-jstart-O[cp1]+1
      imax282i[2]<-istart-3*O[cp2]+3
      jmax282i[2]<-jstart-O[cp2]+1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[28]==1)
     {
      imax28<-imax281i
      jmax28<-jmax281i
      max[28]<-max1
      points(jmax28,row-imax28,pch="。",col="red")
     }
     else if(d[28]==2)
     {
      imax28<-imax282i[1]
      jmax28<-jmax282i[1]
      imax28[2]<-imax282i[2]
      jmax28[2]<-jmax282i[2]
      max[28]<-max2
      points(jmax28[1],row-imax28[1],pch="。",col="red")
      points(jmax28[2],row-imax28[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax28<-imax281i
       jmax28<-jmax281i
       max[28]<-max1
       points(jmax28,row-imax28,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax28<-imax282i[1]
       jmax28<-jmax282i[1]
       imax28[2]<-imax282i[2]
       jmax28[2]<-jmax282i[2]
       max[28]<-max2
       points(jmax28[1],row-imax28[1],pch="。",col="red")
       points(jmax28[2],row-imax28[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[29]==1)
    { 
     imax29<-0
     jmax29<-0
     imax291i<-0
     jmax291i<-0
     imax292i<-0
     jmax292i<-0
     max1<-0
     max2<-0
     s29<-0
     i<-0
     while((istart-3*i>=locate[1])&&(jstart+i<=locate[4])){  
         s29[i+1]<-img[istart-3*i,jstart+i]
         i<-i+1
     }
     n<-length(s29)
     screening(n,s29)
     O<-0
     O<-screening(n,s29)$O
     nO<-screening(n,s29)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s29,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s29,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax291i<-istart-3*O[cp1]-3
      jmax291i<-jstart+O[cp1]-1
      max1<-NMCD[cp1]
     }
     if(d[29]!=1)
     {
      calculate2(s29,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s29,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax292i<-istart-3*O[cp1]+3
      jmax292i<-jstart+O[cp1]-1
      imax292i[2]<-istart-3*O[cp2]+3
      jmax292i[2]<-jstart+O[cp2]-1
      max2<-NMCD2[cp1,cp2]
     }
     if(d[29]==1)
     {
      imax29<-imax291i
      jmax29<-jmax291i
      max[29]<-max1
      points(jmax29,row-imax29,pch="。",col="red")
     }
     else if(d[29]==2)
     {
      imax29<-imax292i[1]
      jmax29<-jmax292i[1]
      imax29[2]<-imax292i[2]
      jmax29[2]<-jmax292i[2]
      max[29]<-max2
      points(jmax29[1],row-imax29[1],pch="。",col="red")
      points(jmax29[2],row-imax29[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax29<-imax291i
       jmax29<-jmax291i
       max[29]<-max1
       points(jmax29,row-imax29,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax29<-imax292i[1]
       jmax29<-jmax292i[1]
       imax29[2]<-imax292i[2]
       jmax29[2]<-jmax292i[2]
       max[29]<-max2
       points(jmax29[1],row-imax29[1],pch="。",col="red")
       points(jmax29[2],row-imax29[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[30]==1)
    { 
     imax30<-0
     jmax30<-0
     imax301i<-0
     jmax301i<-0
     imax302i<-0
     jmax302i<-0
     max1<-0
     max2<-0
     s30<-0
     i<-0
     while((istart-3*i>=locate[1])&&(jstart+2*i<=locate[4])){  
             s30[i+1]<-img[istart-3*i,jstart+2*i]
             i<-i+1
     }
     n<-length(s30)
     screening(n,s30)
     O<-0
     O<-screening(n,s30)$O
     nO<-screening(n,s30)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s30,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s30,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax301i<-istart-3*O[cp1]+3
      jmax301i<-jstart+2*O[cp1]-2
      max1<-NMCD[cp1]
     }
     if(d[30]!=1)
     {
      calculate2(s30,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s30,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax302i<-istart-3*O[cp1]+3
      jmax302i<-jstart+2*O[cp1]-2
      imax302i[2]<-istart-3*O[cp2]+3
      jmax302i[2]<-jstart+2*O[cp2]-2
      max2<-NMCD2[cp1,cp2]
     }
     if(d[30]==1)
     {
      imax30<-imax301i
      jmax30<-jmax301i
      max[30]<-max1
      points(jmax30,row-imax30,pch="。",col="red")
     }
     else if(d[30]==2)
     {
      imax30<-imax302i[1]
      jmax30<-jmax302i[1]
      imax30[2]<-imax302i[2]
      jmax30[2]<-jmax302i[2]
      max[30]<-max2
      points(jmax30[1],row-imax30[1],pch="。",col="red")
      points(jmax30[2],row-imax30[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax30<-imax301i
       jmax30<-jmax301i
       max[30]<-max1
       points(jmax30,row-imax30,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax30<-imax302i[1]
       jmax30<-jmax302i[1]
       imax30[2]<-imax302i[2]
       jmax30[2]<-jmax302i[2]
       max[30]<-max2
       points(jmax30[1],row-imax30[1],pch="。",col="red")
       points(jmax30[2],row-imax30[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[31]==1)
    { 
     imax31<-0
     jmax31<-0
     imax311i<-0
     jmax311i<-0
     imax312i<-0
     jmax312i<-0
     max1<-0
     max2<-0
     s31<-0
     i<-0
     while((istart-2*i>=locate[1])&&(jstart+3*i<=locate[4])){  
             s31[i+1]<-img[istart-2*i,jstart+3*i]
             i<-i+1
     }
     n<-length(s31)
     screening(n,s31)
     O<-0
     O<-screening(n,s31)$O
     nO<-screening(n,s31)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s31,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s31,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax311i<-istart-2*O[cp1]+2
      jmax311i<-jstart+3*O[cp1]-3
      max1<-NMCD[cp1]
     }
     if(d[31]!=1)
     {
      calculate2(s31,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s31,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax312i<-istart-2*O[cp1]+2
      jmax312i<-jstart+3*O[cp1]-3
      imax312i[2]<-istart-2*O[cp2]+2
      jmax312i[2]<-jstart+3*O[cp2]-3
      max2<-NMCD2[cp1,cp2]
     }
     if(d[31]==1)
     {
      imax31<-imax311i
      jmax31<-jmax311i
      max[31]<-max1
      points(jmax31,row-imax31,pch="。",col="red")
     }
     else if(d[31]==2)
     {
      imax31<-imax312i[1]
      jmax31<-jmax312i[1]
      imax31[2]<-imax312i[2]
      jmax31[2]<-jmax312i[2]
      max[31]<-max2
      points(jmax31[1],row-imax31[1],pch="。",col="red")
      points(jmax31[2],row-imax31[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax31<-imax311i
       jmax31<-jmax311i
       max[31]<-max1
       points(jmax31,row-imax31,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax31<-imax312i[1]
       jmax31<-jmax312i[1]
       imax31[2]<-imax312i[2]
       jmax31[2]<-jmax312i[2]
       max[31]<-max2
       points(jmax31[1],row-imax31[1],pch="。",col="red")
       points(jmax31[2],row-imax31[2],pch="。",col="purple")
      }
     } 
    }

    if(dc[32]==1)
    { 
     imax32<-0
     jmax32<-0
     imax321i<-0
     jmax321i<-0
     imax322i<-0
     jmax322i<-0
     max1<-0
     max2<-0
     s32<-0
     i<-0
     while((istart-i>=locate[1])&&(jstart+3*i<=locate[4])){  
         s32[i+1]<-img[istart-i,jstart+3*i]
         i<-i+1
     }
     n<-length(s32)
     screening(n,s32)
     O<-0
     O<-screening(n,s32)$O
     nO<-screening(n,s32)$nO
     zeta<-((log(n))^2)/2 
     {                                                                                    
      calculate1(s32,n,O,nO,istart,jstart)                                                   
      NMCD<-calculate1(s32,n,O,nO,istart,jstart)$NMCD
      NMCD1<-matrix(0,nrow=nO)
      for(a in 1:nO){                                                                         
          if(NMCD[a]!=0)
              NMCD1[a]<-1/NMCD[a]
          else
              NMCD1[a]<-NMCD[a]
      }
      cp1<-which(NMCD1==min(NMCD1))
      imax321i<-istart-O[cp1]+1
      jmax321i<-jstart+3*O[cp1]-3
      max1<-NMCD[cp1]
     }
     if(d[32]!=1)
     {
      calculate2(s32,n,O,nO,istart,jstart)                                                    
      NMCD2<-calculate2(s32,n,O,nO,istart,jstart)$NMCD2
      NMCD21<-matrix(0,nrow=nO,ncol=nO,byrow=T)
      for(a in 1:nO)
          for(b in 1:nO){
              if(NMCD2[a,b]!=0)
                  NMCD21[a,b]<-1/NMCD2[a,b]
              else
                  NMCD21[a,b]<-NMCD2[a,b]
      }
      summax<-which(NMCD21==min(NMCD21))
      cp1<-summax%%(nO)
      cp2<-summax%/%(nO)+1
      imax322i<-istart-O[cp1]+1
      jmax322i<-jstart+3*O[cp1]-3
      imax322i[2]<-istart-O[cp2]+1
      jmax322i[2]<-jstart+3*O[cp2]-3
      max2<-NMCD2[cp1,cp2]
     }
     if(d[32]==1)
     {
      imax32<-imax321i
      jmax32<-jmax321i
      max[32]<-max1
      points(jmax32,row-imax32,pch="。",col="red")
     }
     else if(d[32]==2)
     {
      imax32<-imax322i[1]
      jmax32<-jmax322i[1]
      imax32[2]<-imax322i[2]
      jmax32[2]<-jmax322i[2]
      max[32]<-max2
      points(jmax32[1],row-imax32[1],pch="。",col="red")
      points(jmax32[2],row-imax32[2],pch="。",col="purple")
     }
     else   
     {
      min<-min((-max1+zeta),(-max2+2*zeta))
      if(min==(-max1+zeta))
      { 
       imax32<-imax321i
       jmax32<-jmax321i
       max[32]<-max1
       points(jmax32,row-imax32,pch="。",col="red")
      } 
      else if(min==(-max2+2*zeta))
      {
       imax32<-imax322i[1]
       jmax32<-jmax322i[1]
       imax32[2]<-imax322i[2]
       jmax32[2]<-jmax322i[2]
       max[32]<-max2
       points(jmax32[1],row-imax32[1],pch="。",col="red")
       points(jmax32[2],row-imax32[2],pch="。",col="purple")
      }
     } 
    }
}